/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import Mathlib.Algebra.GCDMonoid.Finset
public import Mathlib.Data.Matrix.Mul
public import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Primitive kernel vectors

A vector over a commutative ring is *primitive* in this file when its coordinates generate the
unit ideal. This file divides a nonzero kernel vector of a matrix by the gcd of its coordinates
and shows that the quotient is a primitive kernel vector. The ring only needs Bézout
coefficients for finite gcds and a normalized gcd; no polynomial structure is used.

## Main statements

* `Finset.span_gcd`: in a Bézout ring with a normalized gcd, the gcd of a finite family generates
  the same ideal as the family.
* `Ideal.span_range_eq_top_iff_univ_gcd_eq_one`: the coordinates of a finite vector generate the
  unit ideal exactly when their gcd is `1`.
* `Ideal.comp_ne_zero_of_span_range_eq_top`: a family that generates the unit ideal has a nonzero
  image under every ring homomorphism into a nontrivial semiring. The index type may be infinite.
* `Matrix.exists_primitive_kernel_vector_eq_smul`: a nonzero kernel vector `v` factors as
  `v = g • u` with `g ≠ 0` and `u` a primitive kernel vector.

The factorization `v = g • u` is the form from which the preservation properties follow. Each
coordinate satisfies `v j = g * u j`, so a zero coordinate of `v` is a zero coordinate of `u`, and
over a polynomial ring the degree of `u j` is at most the degree of `v j`
(`Polynomial.mem_degreeLT_of_mul_left` in `ArkLib.ToMathlib.Polynomial.DegreeLT`).

## Proof outline

`Finset.gcd_eq_sum_mul` writes the gcd of a finite family as a linear combination of its members,
and each member is a multiple of the gcd; together these give `Finset.span_gcd`. A normalized gcd
is a unit exactly when it equals `1`, which gives the unit-ideal criterion. For the matrix
statement, `Finset.extract_gcd` factors `v` through its gcd with a cofactor of gcd `1`, and the
kernel equation for the cofactor follows by cancelling the nonzero gcd. Nonvanishing under a ring
homomorphism uses `Ideal.map`: it sends the unit ideal to the unit ideal, while the ideal
generated by zeros is the zero ideal.

## References

The results are extracted and generalized from `ArkLib.ToMathlib.LinearAlgebra` at immutable
source revision `a5aa2677fee4e3a79d6bb05136631cce4a08587d`. That revision proves
`Matrix.exists_primitive_kernel_vector_preserving_zero` and `Matrix.exists_primitive_kernel_vector`
in `PrimitivePolynomialKernel.lean`, and `Matrix.exists_primitive_kernel_vector_degreeLT` in
`ShiftedDegreeKernel.lean`, for polynomial matrices over a field with `Fin` indices. Each of them
bundles the gcd normalization with coordinate-wise degree, zero-preservation, and specialization
conclusions. Here the normalization holds over any Bézout ring with a normalized gcd and any row
index type, and the other conclusions are derived from `v = g • u` and from
`Ideal.comp_ne_zero_of_span_range_eq_top`.

The shifted and column families of the same revision remain to be ported:
`Matrix.exists_ne_zero_mulVec_eq_zero_shifted_degreeLT` and
`Matrix.exists_primitive_mulVec_eq_zero_of_shifted_surplus` in `ShiftedDegreeKernel.lean`, and
`Matrix.exists_ne_zero_mulVec_eq_zero_column_degreeLT`,
`Matrix.exists_ne_zero_mulVec_eq_zero_column_degreeLT_of_rank`, and
`Matrix.exists_primitive_mulVec_eq_zero_of_column_surplus` in `ColumnDegreeKernel.lean`.
-/

@[expose] public section

namespace Finset

variable {ι R : Type*} [CommRing R] [IsBezout R] [NormalizedGCDMonoid R]

/-- In a Bézout ring with a normalized gcd, the gcd of a finite family generates the same ideal
as the family.

This extends `span_gcd`, which treats two elements, to any finset. The Bézout hypothesis supplies
the coefficients that express `s.gcd f` as a combination of the `f a`
(`Finset.gcd_eq_sum_mul`); the `NormalizedGCDMonoid` instance is what defines `Finset.gcd`. For
`s = ∅` both sides are the zero ideal, because `Finset.gcd` of an empty family is `0`. -/
theorem span_gcd (s : Finset ι) (f : ι → R) : Ideal.span {s.gcd f} = Ideal.span (f '' s) := by
  apply le_antisymm
  · rw [Ideal.span_singleton_le_iff_mem]
    obtain ⟨g, hg⟩ := s.gcd_eq_sum_mul f
    rw [hg]
    exact sum_mem fun a ha ↦ Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨a, ha, rfl⟩)
  · rw [Ideal.span_le]
    rintro _ ⟨a, ha, rfl⟩
    exact Ideal.mem_span_singleton.mpr (s.gcd_dvd ha)

end Finset

namespace Ideal

/-- In a Bézout ring with a normalized gcd, the coordinates of a finite vector generate the unit
ideal exactly when their gcd is `1`.

The direction from `Finset.univ.gcd u = 1` to `Ideal.span (Set.range u) = ⊤` is the one that
needs the Bézout hypothesis. The converse uses that `Finset.gcd` is normalized, so a unit gcd is
equal to `1`. An empty index type has gcd `0` and span `⊥`, so both sides are false unless `R` is
the zero ring. -/
theorem span_range_eq_top_iff_univ_gcd_eq_one {ι R : Type*} [CommRing R] [IsBezout R]
    [NormalizedGCDMonoid R] [Fintype ι] {u : ι → R} :
    Ideal.span (Set.range u) = ⊤ ↔ Finset.univ.gcd u = 1 := by
  rw [← Set.image_univ, ← Finset.coe_univ, ← Finset.span_gcd, Ideal.span_singleton_eq_top,
    ← normalize_eq_one, Finset.normalize_gcd]

/-- A family that generates the unit ideal is not sent to zero by any ring homomorphism into a
nontrivial semiring.

If `Ideal.span (Set.range u) = ⊤` and `φ : R →+* S` with `S` nontrivial, then some `φ (u j)` is
nonzero. The index type may be infinite: the proof maps the unit ideal along `φ` with `Ideal.map`
instead of expanding `1` as a finite combination of the `u j`. The nontriviality of `S` is
necessary, since every family is zero in the zero ring. With `φ := RingHom.id R` the statement
says that `u ≠ 0` whenever `R` is nontrivial. With `φ := Polynomial.eval₂RingHom ι z` it says
that the coordinates of a primitive polynomial vector have no common root `z` in any extension
`ι : F →+* E`. -/
theorem comp_ne_zero_of_span_range_eq_top {ι R S : Type*} [Semiring R] [Semiring S]
    [Nontrivial S] {u : ι → R} (hu : Ideal.span (Set.range u) = ⊤) (φ : R →+* S) :
    (fun j ↦ φ (u j)) ≠ 0 := by
  intro hzero
  have hmap := congrArg (Ideal.map φ) hu
  rw [Ideal.map_span, Ideal.map_top, ← Set.range_comp] at hmap
  have hcomp : ⇑φ ∘ u = 0 := hzero
  rw [hcomp, Ideal.span_eq_bot.mpr (by simp)] at hmap
  exact bot_ne_top hmap

end Ideal

namespace Matrix

/-- A nonzero kernel vector over a Bézout ring with a normalized gcd is a nonzero multiple of a
primitive kernel vector.

For `M *ᵥ v = 0` and `v ≠ 0`, there are `g ≠ 0` and `u` with `v = g • u`, `u ≠ 0`,
`M *ᵥ u = 0`, and `Ideal.span (Set.range u) = ⊤`. The proof takes `g` to be
`Finset.univ.gcd v`; the statement only records that `g` is nonzero.

The factorization carries the properties that normalization preserves. Each coordinate satisfies
`v j = g * u j`, so `v j = 0` forces `u j = 0`, and over a polynomial ring `u j` has degree at most
that of `v j` (`Polynomial.mem_degreeLT_of_mul_left` in `ArkLib.ToMathlib.Polynomial.DegreeLT`).
The hypothesis `v ≠ 0` is needed because the zero vector has gcd `0`. No `IsDomain` hypothesis is
needed: a `GCDMonoid` cancels nonzero factors, and `v ≠ 0` makes `R` nontrivial. The row index
type `m` is arbitrary, since only the finitely many columns enter `M *ᵥ v`. -/
theorem exists_primitive_kernel_vector_eq_smul {m n R : Type*} [Fintype n] [CommRing R]
    [IsBezout R] [NormalizedGCDMonoid R] (M : Matrix m n R) {v : n → R} (hv : v ≠ 0)
    (hMv : M *ᵥ v = 0) :
    ∃ (g : R) (u : n → R), g ≠ 0 ∧ v = g • u ∧ u ≠ 0 ∧ M *ᵥ u = 0 ∧
      Ideal.span (Set.range u) = ⊤ := by
  obtain ⟨j₀, hj₀⟩ := Function.ne_iff.mp hv
  obtain ⟨u, hvu, hu⟩ := Finset.univ.extract_gcd v ⟨j₀, Finset.mem_univ _⟩
  have hg : Finset.univ.gcd v ≠ 0 :=
    Finset.gcd_ne_zero_iff.mpr ⟨j₀, Finset.mem_univ _, hj₀⟩
  have hv_eq : v = Finset.univ.gcd v • u := funext fun j ↦ hvu j (Finset.mem_univ j)
  refine ⟨_, u, hg, hv_eq, ?_, ?_, Ideal.span_range_eq_top_iff_univ_gcd_eq_one.mpr hu⟩
  · rintro rfl
    exact hv (by simpa using hv_eq)
  · rw [hv_eq, mulVec_smul] at hMv
    exact (smul_eq_zero.mp hMv).resolve_left hg

end Matrix
