/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
import ArkLib.ToCompPoly.Univariate.Basic
import CompPoly.Univariate.EuclideanAlgorithm
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Executable inversion in a polynomial quotient

This file uses `CompPoly.CPolynomial.normXgcd` to compute an inverse behind a
coprimality guard, proves its modular multiplication contract, and interprets
the result in the proof-facing quotient `F[X] / (modulus)`.
-/

namespace CompPoly.CPolynomial

variable {F : Type*} [Field F] [BEq F] [LawfulBEq F]

/-- Return the Bézout coefficient of `a` exactly when normalized extended gcd
certifies that `a` and `modulus` are coprime. -/
def inverseMod? (a modulus : CPolynomial F) : Option (CPolynomial F) :=
  let result := normXgcd a modulus
  if result.1 == 1 then some result.2.1 else none

theorem inverseMod?_eq_none_iff (a modulus : CPolynomial F) :
    inverseMod? a modulus = none ↔ (normXgcd a modulus).1 ≠ 1 := by
  simp [inverseMod?, beq_iff_eq]

theorem inverseMod?_eq_some_iff (a modulus inverse : CPolynomial F) :
    inverseMod? a modulus = some inverse ↔
      (normXgcd a modulus).1 = 1 ∧ inverse = (normXgcd a modulus).2.1 := by
  by_cases hgcd : (normXgcd a modulus).1 = 1
  · have hout : inverseMod? a modulus = some (normXgcd a modulus).2.1 := by
      simp [inverseMod?, hgcd]
    constructor
    · intro hin
      refine ⟨hgcd, ?_⟩
      exact Option.some.inj (hin.symm.trans hout)
    · rintro ⟨_, rfl⟩
      exact hout
  · simp [inverseMod?, beq_iff_eq, hgcd]

/-- A returned Bézout coefficient is a multiplicative inverse modulo a monic
polynomial. The right side is reduced as well, covering the unit modulus. -/
theorem inverseMod?_mul_modByMonic {a modulus inverse : CPolynomial F}
    (hmodulus : modulus.monic) (hinverse : inverseMod? a modulus = some inverse) :
    (a * inverse).modByMonic modulus = (1 : CPolynomial F).modByMonic modulus := by
  obtain ⟨hgcd, hinverse⟩ := (inverseMod?_eq_some_iff a modulus inverse).mp hinverse
  have hbezout := normXgcd_bezout a modulus 0
  simp only [Bezout] at hbezout
  apply toPoly_injective
  rw [modByMonic_toPoly_eq_modByMonic _ _ hmodulus,
    modByMonic_toPoly_eq_modByMonic _ _ hmodulus, toPoly_mul, toPoly_one]
  apply Polynomial.modByMonic_eq_of_dvd_sub ((monic_toPoly_iff modulus).mp hmodulus)
  refine ⟨-(normXgcd a modulus).2.2.toPoly, ?_⟩
  have hbezoutPoly := congrArg (CPolynomial.toPoly (R := F)) hbezout
  rw [hgcd, toPoly_one, toPoly_add, toPoly_mul, toPoly_mul] at hbezoutPoly
  rw [← hinverse] at hbezoutPoly
  calc
    a.toPoly * inverse.toPoly - 1 =
        -((normXgcd a modulus).2.2.toPoly * modulus.toPoly) := by
      rw [hbezoutPoly]
      ring
    _ = modulus.toPoly * -(normXgcd a modulus).2.2.toPoly := by ring

end CompPoly.CPolynomial

namespace ArkLib.PolynomialQuotient

open CompPoly CompPoly.CPolynomial Polynomial

variable {F : Type*} [Field F] [BEq F] [LawfulBEq F]

/-- The principal ideal generated by a computable modulus. -/
noncomputable def modIdeal (modulus : CPolynomial F) : Ideal (Polynomial F) :=
  Ideal.span {modulus.toPoly}

/-- The proof-facing polynomial quotient by `modulus`. -/
abbrev ModAlgebra (modulus : CPolynomial F) : Type _ :=
  Polynomial F ⧸ modIdeal modulus

/-- Executable canonical reduction when `modulus` is monic. -/
def reduce (modulus p : CPolynomial F) : CPolynomial F :=
  p.modByMonic modulus

/-- Interpret a computable polynomial in the proof-facing quotient. -/
noncomputable def quotientHom (modulus : CPolynomial F) :
    CPolynomial F →+* ModAlgebra modulus :=
  (Ideal.Quotient.mk (modIdeal modulus)).comp
    (CPolynomial.ringEquiv : CPolynomial F ≃+* Polynomial F).toRingHom

@[simp] theorem quotientHom_apply (modulus p : CPolynomial F) :
    quotientHom modulus p = Ideal.Quotient.mk (modIdeal modulus) p.toPoly := rfl

/-- Executable monic reduction preserves the represented quotient element. -/
@[simp] theorem quotientHom_reduce {modulus : CPolynomial F} (hmodulus : modulus.monic)
    (p : CPolynomial F) : quotientHom modulus (reduce modulus p) = quotientHom modulus p := by
  rw [quotientHom_apply, quotientHom_apply, reduce,
    CPolynomial.modByMonic_toPoly_eq_modByMonic _ _ hmodulus, Ideal.Quotient.eq]
  have h : p.toPoly %ₘ modulus.toPoly - p.toPoly =
      -(modulus.toPoly * (p.toPoly /ₘ modulus.toPoly)) := by
    rw [Polynomial.modByMonic_eq_sub_mul_div]
    ring
  rw [h, modIdeal]
  exact neg_mem (Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _))

@[simp] theorem quotientHom_modulus (modulus : CPolynomial F) :
    quotientHom modulus modulus = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)

/-- `inverseMod?` success is interpreted as a unit equation in the quotient. -/
theorem quotientHom_mul_inverseMod?_eq_one {a modulus inverse : CPolynomial F}
    (hmodulus : modulus.monic)
    (hinverse : inverseMod? a modulus = some inverse) :
    quotientHom modulus a * quotientHom modulus inverse = 1 := by
  rw [← map_mul]
  calc
    quotientHom modulus (a * inverse) = quotientHom modulus (reduce modulus (a * inverse)) :=
      (quotientHom_reduce hmodulus _).symm
    _ = quotientHom modulus (reduce modulus 1) := by
      exact congrArg (quotientHom modulus)
        (inverseMod?_mul_modByMonic hmodulus hinverse)
    _ = quotientHom modulus 1 := quotientHom_reduce hmodulus _
    _ = 1 := map_one _

end ArkLib.PolynomialQuotient
