/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.Data.Polynomial.Differential.TaylorChart
public import ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineHilbertCutFamily
public import ArkLib.ToMathlib.RingTheory.Nullstellensatz

/-!
# Loci in the rational Taylor chart

Let `Q` be a differential polynomial of order `r` over a field `F`, fix a center, and write `S`
for the initial separant. This file describes, as zero loci in the initial jet space `F^{r+1}`,
the sets that the rational Taylor chart of `Q` cuts out.

* `highTaylorCutsIdeal center Q K k τ` is the ideal generated by the common numerators
  `commonTaylorNumerator center Q τ l` for `k ≤ l < K`. On `S ≠ 0` its zeros are the initial jets
  whose reconstructed polynomial has degree below `k`.
* `regularAgreementCutLocus I center Q K τ domain received` is the set of zeros of an ideal `I` at
  which `S ≠ 0` and every agreement equation `taylorAgreementEquation` at
  `(domain i, received i)` vanishes. When `I` contains the high cuts and the agreement points
  include `k` distinct ones, this set has at most one point.
* `initialJetPrimeFamily center Q` is the finite family of minimal primes over the initial
  equation that do not contain `S`. Every zero of the initial equation with `S ≠ 0`, over any
  extension field, lies on one of them. Each member has dimension `r` (its affine Hilbert
  polynomial has natural degree `r`), and for every weight `b` the potential
  `∑ P, affineDegree P * b ^ dim P` of the family is at most `jetTotalDegree Q * b ^ r`.

The last part places polynomial solutions in these loci. In an infinite domain, finitely many
solutions with nonzero separant specialization share a center at which all their separants are
nonzero. At such a center, the Hasse jet of a solution of degree below `k` lies on the initial
hypersurface and on the high cuts, and the jets of distinct solutions of degree below `K` are
distinct.

## Main statements

* `mem_zeroLocus_highTaylorCutsIdeal_iff`: the zeros of the high cuts.
* `regularAgreementCutLocus_subsingleton` and `eq_of_mem_zeroLocus_of_highTaylorCutsIdeal_le`:
  high cuts and agreement at `k` distinct points leave at most one regular jet.
* `exists_mem_initialJetPrimeFamily_of_regular`: regular points of the initial hypersurface lie
  on retained prime components.
* `natDegree_affineHilbertPolynomial_of_mem_initialJetPrimeFamily` and
  `sum_affineDegree_mul_pow_initialJetPrimeFamily_le_jetTotalDegree`: the dimension and the
  potential of the retained components.
* `exists_forall_jetEvaluation_ne_zero`: a common center for finitely many solutions.
* `injOn_polynomialJet` and `card_image_polynomialJet`: Hasse jets separate regular solutions.
* `polynomialJet_mem_zeroLocus_initialJetEquation_sup_highTaylorCutsIdeal` and
  `polynomialJet_mem_regularAgreementCutLocus`: regular solutions lie in these loci.

## References

* [Dao, Q., Kominers, S. D., and Thaler, J., *Reed–Solomon Codes Beyond Johnson: Efficient
  Decoding and Smaller Cryptographic Proofs*][DKT26], Appendix A.6.
-/

@[expose] public section

namespace PolynomialDifferential

noncomputable section

open MvPolynomial

/-! ### A common regular center -/

/-- In an infinite domain, finitely many polynomials `P` with nonzero specialization
`differentialSpecialization D P` admit a common center `a` at which
`jetEvaluation D a (polynomialJet a P)` is nonzero for all of them. -/
theorem exists_forall_jetEvaluation_ne_zero {R : Type*} [CommRing R] [IsDomain R] [Infinite R]
    {d : ℕ} (D : DifferentialPolynomial R d) (T : Finset (Polynomial R))
    (hT : ∀ P ∈ T, differentialSpecialization D P ≠ 0) :
    ∃ center : R, ∀ P ∈ T, jetEvaluation D center (polynomialJet center P) ≠ 0 := by
  classical
  have hprod : ∏ P ∈ T, differentialSpecialization D P ≠ 0 := Finset.prod_ne_zero_iff.mpr hT
  obtain ⟨center, hc⟩ :
      ∃ center : R, (∏ P ∈ T, differentialSpecialization D P).eval center ≠ 0 := by
    by_contra! h
    exact hprod (Polynomial.funext (by simpa using h))
  refine ⟨center, fun P hP ↦ ?_⟩
  rw [← eval_differentialSpecialization]
  rw [Polynomial.eval_prod, Finset.prod_ne_zero_iff] at hc
  exact hc P hP

variable {F : Type*} [Field F] {r : ℕ}

/-! ### High cuts -/

/-- The ideal generated by the common numerators `commonTaylorNumerator center Q τ l` of the
rational Taylor coefficients `c_l` for `k ≤ l < K`. -/
def highTaylorCutsIdeal (center : F) (Q : DifferentialPolynomial F r) (K k τ : ℕ) :
    Ideal (MvPolynomial (Fin (r + 1)) F) :=
  Ideal.span (commonTaylorNumerator center Q τ '' Set.Ico k K)

/-- The common numerator of `c_l` lies in the high-cuts ideal for `k ≤ l < K`. -/
theorem commonTaylorNumerator_mem_highTaylorCutsIdeal (center : F)
    (Q : DifferentialPolynomial F r) {K k τ l : ℕ} (hkl : k ≤ l) (hlK : l < K) :
    commonTaylorNumerator center Q τ l ∈ highTaylorCutsIdeal center Q K k τ :=
  Ideal.subset_span ⟨l, ⟨hkl, hlK⟩, rfl⟩

/-- The high-cuts ideal lies in `I` exactly when `I` contains the common numerators of `c_l` for
`k ≤ l < K`. -/
theorem highTaylorCutsIdeal_le_iff (center : F) (Q : DifferentialPolynomial F r) {K k τ : ℕ}
    {I : Ideal (MvPolynomial (Fin (r + 1)) F)} :
    highTaylorCutsIdeal center Q K k τ ≤ I ↔
      ∀ l, k ≤ l → l < K → commonTaylorNumerator center Q τ l ∈ I := by
  rw [highTaylorCutsIdeal, Ideal.span_le, Set.image_subset_iff]
  exact ⟨fun h l hkl hlK ↦ h ⟨hkl, hlK⟩, fun h l hl ↦ h l hl.1 hl.2⟩

/-- A point over an extension field is a zero of the high-cuts ideal exactly when the common
numerators of `c_l` vanish there for `k ≤ l < K`. -/
theorem mem_zeroLocus_highTaylorCutsIdeal_iff (center : F) (Q : DifferentialPolynomial F r)
    {K k τ : ℕ} {E : Type*} [Field E] [Algebra F E] {jet : Fin (r + 1) → E} :
    jet ∈ zeroLocus E (highTaylorCutsIdeal center Q K k τ) ↔
      ∀ l, k ≤ l → l < K → aeval jet (commonTaylorNumerator center Q τ l) = 0 := by
  rw [highTaylorCutsIdeal, zeroLocus_span]
  simp only [Set.mem_ofPred_eq, Set.forall_mem_image, Set.mem_Ico, and_imp]

/-- If the high cuts lie in `I`, the common numerators of `c_l` for `k ≤ l < K` vanish at every
zero of `I`. -/
theorem aeval_commonTaylorNumerator_eq_zero_of_mem_zeroLocus (center : F)
    (Q : DifferentialPolynomial F r) {K k τ : ℕ} {I : Ideal (MvPolynomial (Fin (r + 1)) F)}
    (hhigh : highTaylorCutsIdeal center Q K k τ ≤ I) {E : Type*} [Field E] [Algebra F E]
    {jet : Fin (r + 1) → E} (hjet : jet ∈ zeroLocus E I) :
    ∀ l, k ≤ l → l < K → aeval jet (commonTaylorNumerator center Q τ l) = 0 :=
  (mem_zeroLocus_highTaylorCutsIdeal_iff center Q).mp (zeroLocus_anti_mono hhigh hjet)

/-! ### Regular agreement loci -/

/-- The zeros of `I` at which the initial separant is nonzero and the agreement equation at
`(domain i, received i)` vanishes for every `i`. -/
def regularAgreementCutLocus (I : Ideal (MvPolynomial (Fin (r + 1)) F)) (center : F)
    (Q : DifferentialPolynomial F r) (K τ : ℕ) {ι : Type*} (domain received : ι → F) :
    Set (Fin (r + 1) → F) :=
  {jet | jet ∈ zeroLocus F I ∧ aeval jet (initialJetSeparant center Q) ≠ 0 ∧
    ∀ i, aeval jet (taylorAgreementEquation center Q K τ (domain i) (received i)) = 0}

/-- Membership in the regular agreement locus. -/
theorem mem_regularAgreementCutLocus {I : Ideal (MvPolynomial (Fin (r + 1)) F)} {center : F}
    {Q : DifferentialPolynomial F r} {K τ : ℕ} {ι : Type*} {domain received : ι → F}
    {jet : Fin (r + 1) → F} :
    jet ∈ regularAgreementCutLocus I center Q K τ domain received ↔
      jet ∈ zeroLocus F I ∧ aeval jet (initialJetSeparant center Q) ≠ 0 ∧
        ∀ i, aeval jet (taylorAgreementEquation center Q K τ (domain i) (received i)) = 0 :=
  Iff.rfl

/-- Let `r < K`, let `τ` be sufficient for `K`, and let `I` contain the high cuts for `k`. Two
zeros of `I` with nonzero separant, at which the agreement equations at
`(domain i, received i)` vanish for all `i ∈ T`, are equal, provided `domain` is injective on `T`
and `k ≤ #T`. -/
theorem eq_of_mem_zeroLocus_of_highTaylorCutsIdeal_le (center : F)
    (Q : DifferentialPolynomial F r) {K τ : ℕ} (hτ : TaylorExponentSufficient r K τ)
    (hK : r < K) {k : ℕ} {I : Ideal (MvPolynomial (Fin (r + 1)) F)}
    (hhigh : highTaylorCutsIdeal center Q K k τ ≤ I) {ι : Type*} (domain received : ι → F)
    (T : Finset ι) (hinj : Set.InjOn domain T) (hk : k ≤ T.card) {jet jet' : Fin (r + 1) → F}
    (hjet : jet ∈ zeroLocus F I) (hjet' : jet' ∈ zeroLocus F I)
    (hS : aeval jet (initialJetSeparant center Q) ≠ 0)
    (hS' : aeval jet' (initialJetSeparant center Q) ≠ 0)
    (hcut : ∀ i ∈ T,
      aeval jet (taylorAgreementEquation center Q K τ (domain i) (received i)) = 0)
    (hcut' : ∀ i ∈ T,
      aeval jet' (taylorAgreementEquation center Q K τ (domain i) (received i)) = 0) :
    jet = jet' :=
  eq_of_highTaylorCuts_of_agreement center Q hτ hK domain received T hinj hk hS hS'
    (aeval_commonTaylorNumerator_eq_zero_of_mem_zeroLocus center Q hhigh hjet)
    (aeval_commonTaylorNumerator_eq_zero_of_mem_zeroLocus center Q hhigh hjet') hcut hcut'

/-- Let `r < K`, let `τ` be sufficient for `K`, and let `I` contain the high cuts for `k`. If
`domain` is injective on a finite index type with at least `k` elements, the regular agreement
locus of `I` has at most one point. -/
theorem regularAgreementCutLocus_subsingleton (center : F) (Q : DifferentialPolynomial F r)
    {K τ : ℕ} (hτ : TaylorExponentSufficient r K τ) (hK : r < K) {k : ℕ}
    {I : Ideal (MvPolynomial (Fin (r + 1)) F)} (hhigh : highTaylorCutsIdeal center Q K k τ ≤ I)
    {ι : Type*} [Fintype ι] (domain received : ι → F) (hinj : Function.Injective domain)
    (hk : k ≤ Fintype.card ι) :
    (regularAgreementCutLocus I center Q K τ domain received).Subsingleton := by
  rintro jet ⟨hjet, hS, hcut⟩ jet' ⟨hjet', hS', hcut'⟩
  exact eq_of_mem_zeroLocus_of_highTaylorCutsIdeal_le center Q hτ hK hhigh domain received
    Finset.univ hinj.injOn (by simpa using hk) hjet hjet' hS hS' (fun i _ ↦ hcut i)
    (fun i _ ↦ hcut' i)

/-! ### Retained components of the initial hypersurface -/

/-- The minimal primes over the initial equation that do not contain the initial separant: the
prime components of the initial hypersurface that meet the open set `S ≠ 0`. -/
def initialJetPrimeFamily (center : F) (Q : DifferentialPolynomial F r) :
    Finset (Ideal (MvPolynomial (Fin (r + 1)) F)) :=
  (Ideal.span {initialJetEquation center Q}).retainedMinimalPrimes (initialJetSeparant center Q)

/-- An ideal belongs to the initial prime family exactly when it is a minimal prime over the
initial equation not containing the initial separant. -/
theorem mem_initialJetPrimeFamily {center : F} {Q : DifferentialPolynomial F r}
    {P : Ideal (MvPolynomial (Fin (r + 1)) F)} :
    P ∈ initialJetPrimeFamily center Q ↔
      P ∈ (Ideal.span {initialJetEquation center Q}).minimalPrimes ∧
        initialJetSeparant center Q ∉ P :=
  Ideal.mem_retainedMinimalPrimes

/-- Every member of the initial prime family is prime. -/
theorem isPrime_of_mem_initialJetPrimeFamily {center : F} {Q : DifferentialPolynomial F r}
    {P : Ideal (MvPolynomial (Fin (r + 1)) F)} (hP : P ∈ initialJetPrimeFamily center Q) :
    P.IsPrime :=
  (mem_initialJetPrimeFamily.mp hP).1.1.1

/-- Every member of the initial prime family contains the initial equation. -/
theorem initialJetEquation_mem_of_mem_initialJetPrimeFamily {center : F}
    {Q : DifferentialPolynomial F r} {P : Ideal (MvPolynomial (Fin (r + 1)) F)}
    (hP : P ∈ initialJetPrimeFamily center Q) : initialJetEquation center Q ∈ P :=
  (Ideal.span_singleton_le_iff_mem P).mp (mem_initialJetPrimeFamily.mp hP).1.1.2

/-- No member of the initial prime family contains the initial separant. -/
theorem initialJetSeparant_notMem_of_mem_initialJetPrimeFamily {center : F}
    {Q : DifferentialPolynomial F r} {P : Ideal (MvPolynomial (Fin (r + 1)) F)}
    (hP : P ∈ initialJetPrimeFamily center Q) : initialJetSeparant center Q ∉ P :=
  (mem_initialJetPrimeFamily.mp hP).2

/-- Every zero of the initial equation over an extension field at which the initial separant does
not vanish is a zero of some member of the initial prime family. -/
theorem exists_mem_initialJetPrimeFamily_of_regular {E : Type*} [Field E] [Algebra F E]
    (center : F) (Q : DifferentialPolynomial F r) (jet : Fin (r + 1) → E)
    (hinit : aeval jet (initialJetEquation center Q) = 0)
    (hS : aeval jet (initialJetSeparant center Q) ≠ 0) :
    ∃ P ∈ initialJetPrimeFamily center Q, jet ∈ zeroLocus E P :=
  exists_retainedMinimalPrime_of_mem_zeroLocus _ _ jet (by simpa [zeroLocus_span] using hinit) hS

/-- If some ideal does not contain the initial separant, the initial equation is nonzero. -/
theorem initialJetEquation_ne_zero_of_initialJetSeparant_notMem {center : F}
    {Q : DifferentialPolynomial F r} {P : Ideal (MvPolynomial (Fin (r + 1)) F)}
    (hS : initialJetSeparant center Q ∉ P) : initialJetEquation center Q ≠ 0 :=
  initialJetEquation_ne_zero_of_initialJetSeparant_ne_zero center Q
    fun h ↦ hS (by rw [h]; exact P.zero_mem)

/-- Every member of the initial prime family has dimension `r`: its affine Hilbert polynomial has
natural degree `r`. -/
theorem natDegree_affineHilbertPolynomial_of_mem_initialJetPrimeFamily {center : F}
    {Q : DifferentialPolynomial F r} {P : Ideal (MvPolynomial (Fin (r + 1)) F)}
    (hP : P ∈ initialJetPrimeFamily center Q) : (affineHilbertPolynomial P).natDegree = r := by
  have h := natDegree_affineHilbertPolynomial_add_one_of_mem_minimalPrimes_span_singleton
    (initialJetEquation_ne_zero_of_initialJetSeparant_notMem
      (initialJetSeparant_notMem_of_mem_initialJetPrimeFamily hP))
    (mem_initialJetPrimeFamily.mp hP).1
  rw [Nat.card_eq_fintype_card, Fintype.card_fin] at h
  omega

/-- If the initial equation has total degree at most `v`, then for every weight `b` the members
`P` of the initial prime family satisfy `∑ P, affineDegree P * b ^ dim P ≤ v * b ^ r`, where
`dim P` is the natural degree of the affine Hilbert polynomial of `P`. -/
theorem sum_affineDegree_mul_pow_initialJetPrimeFamily_le (center : F)
    (Q : DifferentialPolynomial F r) {v : ℕ} (hv : (initialJetEquation center Q).totalDegree ≤ v)
    (b : ℕ) :
    ∑ P ∈ initialJetPrimeFamily center Q,
        affineDegree P * (b : ℚ) ^ (affineHilbertPolynomial P).natDegree ≤ v * (b : ℚ) ^ r := by
  rcases (initialJetPrimeFamily center Q).eq_empty_or_nonempty with h | ⟨P, hP⟩
  · rw [h, Finset.sum_empty]
    positivity
  have h := sum_affineDegree_mul_pow_retainedMinimalPrimes_span_singleton_le
    (initialJetEquation_ne_zero_of_initialJetSeparant_notMem
      (initialJetSeparant_notMem_of_mem_initialJetPrimeFamily hP))
    (initialJetSeparant center Q) hv b
  rwa [Nat.card_eq_fintype_card, Fintype.card_fin, Nat.add_sub_cancel] at h

/-- For every weight `b`, the members `P` of the initial prime family satisfy
`∑ P, affineDegree P * b ^ dim P ≤ jetTotalDegree Q * b ^ r`. -/
theorem sum_affineDegree_mul_pow_initialJetPrimeFamily_le_jetTotalDegree (center : F)
    (Q : DifferentialPolynomial F r) (b : ℕ) :
    ∑ P ∈ initialJetPrimeFamily center Q,
        affineDegree P * (b : ℚ) ^ (affineHilbertPolynomial P).natDegree ≤
      jetTotalDegree Q * (b : ℚ) ^ r :=
  sum_affineDegree_mul_pow_initialJetPrimeFamily_le center Q
    (totalDegree_initialJetEquation_le center Q) b

/-! ### Polynomial solutions in the chart loci -/

/-- The Hasse jets at `center` separate the polynomial solutions of degree below `K` whose
separant at the jet is nonzero, provided the binomial pivots `(i choose r)` for `r < i < K` are
nonzero. -/
theorem injOn_polynomialJet (center : F) (Q : DifferentialPolynomial F r) (K : ℕ)
    (hbin : ∀ i, r < i → i < K → (i.choose r : F) ≠ 0) :
    Set.InjOn (polynomialJet (d := r) center)
      {P | P.degree < K ∧ differentialSpecialization Q P = 0 ∧
        jetEvaluation (separant Q (Fin.last r)) center (polynomialJet center P) ≠ 0} := by
  rintro P ⟨hP, hsol, hsep⟩ P' ⟨hP', hsol', hsep'⟩ hjet
  rw [← rationalTaylorPolynomial_polynomialJet center Q P hsol hsep hP hbin, hjet,
    rationalTaylorPolynomial_polynomialJet center Q P' hsol' hsep' hP' hbin]

/-- The Hasse jets at `center` of a finite family of polynomial solutions of degree below `K` with
nonzero separant at the jet are pairwise distinct, provided the binomial pivots `(i choose r)` for
`r < i < K` are nonzero. -/
theorem card_image_polynomialJet [DecidableEq (Fin (r + 1) → F)] (center : F)
    (Q : DifferentialPolynomial F r) (K : ℕ) (hbin : ∀ i, r < i → i < K → (i.choose r : F) ≠ 0)
    (T : Finset (Polynomial F)) (hdegree : ∀ P ∈ T, P.degree < K)
    (hsol : ∀ P ∈ T, differentialSpecialization Q P = 0)
    (hsep : ∀ P ∈ T,
      jetEvaluation (separant Q (Fin.last r)) center (polynomialJet center P) ≠ 0) :
    (T.image (polynomialJet (d := r) center)).card = T.card :=
  Finset.card_image_of_injOn fun P hP P' hP' ↦ injOn_polynomialJet center Q K hbin
    ⟨hdegree P hP, hsol P hP, hsep P hP⟩ ⟨hdegree P' hP', hsol P' hP', hsep P' hP'⟩

/-- The Hasse jet of a polynomial solution of degree below `k` with nonzero separant at the jet
is a zero of the high cuts for `k`, provided the binomial pivots `(i choose r)` for `r < i < K`
are nonzero. -/
theorem polynomialJet_mem_zeroLocus_highTaylorCutsIdeal (center : F)
    (Q : DifferentialPolynomial F r) (P : Polynomial F)
    (hsolution : differentialSpecialization Q P = 0)
    (hseparant : jetEvaluation (separant Q (Fin.last r)) center (polynomialJet center P) ≠ 0)
    {K k : ℕ} (τ : ℕ) (hP : P.degree < k) (hbin : ∀ i, r < i → i < K → (i.choose r : F) ≠ 0) :
    polynomialJet center P ∈ zeroLocus F (highTaylorCutsIdeal center Q K k τ) := by
  rw [mem_zeroLocus_highTaylorCutsIdeal_iff]
  intro l hkl hlK
  apply aeval_commonTaylorNumerator_eq_zero center Q _ τ (by rwa [aeval_initialJetSeparant])
  rw [rationalTaylorCoefficient_eq_solution center Q P hsolution hseparant l
    (fun i hi hil ↦ hbin i hi (hil.trans_lt hlK))]
  apply Polynomial.coeff_eq_zero_of_degree_lt
  rw [Polynomial.degree_taylor]
  exact hP.trans_le (by exact_mod_cast hkl)

/-- The Hasse jet of a polynomial solution of degree below `k` with nonzero separant at the jet
is a zero of the initial equation and of the high cuts for `k` at which the initial separant does
not vanish, provided the binomial pivots `(i choose r)` for `r < i < K` are nonzero. -/
theorem polynomialJet_mem_zeroLocus_initialJetEquation_sup_highTaylorCutsIdeal (center : F)
    (Q : DifferentialPolynomial F r) (P : Polynomial F)
    (hsolution : differentialSpecialization Q P = 0)
    (hseparant : jetEvaluation (separant Q (Fin.last r)) center (polynomialJet center P) ≠ 0)
    {K k : ℕ} (τ : ℕ) (hP : P.degree < k) (hbin : ∀ i, r < i → i < K → (i.choose r : F) ≠ 0) :
    polynomialJet center P ∈
        zeroLocus F (Ideal.span {initialJetEquation center Q} ⊔
          highTaylorCutsIdeal center Q K k τ) ∧
      aeval (polynomialJet center P) (initialJetSeparant center Q) ≠ 0 := by
  refine ⟨?_, by rwa [aeval_initialJetSeparant]⟩
  rw [zeroLocus_sup]
  refine ⟨?_, polynomialJet_mem_zeroLocus_highTaylorCutsIdeal center Q P hsolution hseparant τ hP
    hbin⟩
  simpa [zeroLocus_span] using aeval_initialJetEquation_polynomialJet center Q P hsolution

/-- The Hasse jet of a polynomial solution `P` of degree below `K` with nonzero separant at the
jet lies in the regular agreement locus of any ideal `I` vanishing at it, whenever `P` takes the
value `received i` at `domain i` for every `i`, `τ` is sufficient for `K`, and the binomial pivots
`(i choose r)` for `r < i < K` are nonzero. -/
theorem polynomialJet_mem_regularAgreementCutLocus (center : F)
    (Q : DifferentialPolynomial F r) (P : Polynomial F)
    (hsolution : differentialSpecialization Q P = 0)
    (hseparant : jetEvaluation (separant Q (Fin.last r)) center (polynomialJet center P) ≠ 0)
    {K τ : ℕ} (hτ : TaylorExponentSufficient r K τ) (hP : P.degree < K)
    (hbin : ∀ i, r < i → i < K → (i.choose r : F) ≠ 0)
    {I : Ideal (MvPolynomial (Fin (r + 1)) F)} (hI : polynomialJet center P ∈ zeroLocus F I)
    {ι : Type*} (domain received : ι → F) (hagree : ∀ i, P.eval (domain i) = received i) :
    polynomialJet center P ∈ regularAgreementCutLocus I center Q K τ domain received :=
  ⟨hI, by rwa [aeval_initialJetSeparant], fun i ↦
    (taylorAgreementEquation_eq_zero_iff center Q hτ (polynomialJet center P)
      (by rwa [aeval_initialJetSeparant]) _ _).mpr
        (by rw [rationalTaylorPolynomial_polynomialJet center Q P hsolution hseparant hP hbin]
            exact hagree i)⟩

end

end PolynomialDifferential
