/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.RingTheory.Ideal.Operations

/-!
# Zero- and first-order Taylor congruences for multivariate polynomials

Let `f : R →+* S`, let `a, d : σ → S`, and let `I` be an ideal of `S` containing every coordinate
of `d`. Evaluating a multivariate polynomial `p` at `a + d` agrees modulo `I ^ 2` with evaluating
at `a` and adding the formal linear term `∑ᵢ (∂p/∂xᵢ)(a) * dᵢ`. At order zero: if `a i - b i ∈ I`
for every `i`, then `p(a) - p(b) ∈ I`.

Nothing beyond commutativity is needed: no field, characteristic or degree hypothesis. The
first-order statement is proved over commutative semirings in the form
`p(a + d) = p(a) + (linear term) + e` with `e ∈ I ^ 2`; the subtraction and divisibility forms
need a commutative ring `S`.

## Main statements

* `MvPolynomial.firstOrderIncrement`: the linear term `∑ i ∈ s, (∂p/∂xᵢ)(a) * dᵢ`.
* `MvPolynomial.exists_mem_sq_eval₂Hom_add_eq`: the first-order Taylor formula modulo `I ^ 2`
  over commutative semirings.
* `MvPolynomial.eval₂Hom_add_sub_firstOrderIncrement_mem_sq`: its subtraction form.
* `MvPolynomial.pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement` and
  `pow_succ_dvd_eval₂Hom_add_sub_pderiv`: the divisibility forms modulo `u ^ (k + 1)` when the
  perturbation is divisible by `u ^ k`, `0 < k`; in the second only one pivot coordinate is not
  already divisible by `u ^ (k + 1)`.
* `MvPolynomial.eval₂Hom_sub_eval₂Hom_mem` and `dvd_eval₂Hom_sub_eval₂Hom`: the zero-order
  congruence.

## References

Ported from `ArkLib/ToMathlib/MvPolynomial/FirstOrderTaylor.lean` at ArkLib revision
a5aa2677fee4e3a79d6bb05136631cce4a08587d.

* `firstOrderIncrement`, `firstOrderIncrement_add`,
  `eval₂Hom_add_sub_firstOrderIncrement_mem_sq`,
  `eval₂Hom_add_sub_firstOrderIncrement_univ_mem_sq`,
  `pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement` and `pow_succ_dvd_eval₂Hom_add_sub_pderiv`
  keep their statements. The source required both `R` and `S` to be commutative rings; here `R`
  is a commutative semiring throughout and `firstOrderIncrement` also allows a semiring `S`.
* `exists_mem_sq_eval₂Hom_add_eq` is new: the subtraction-free form over commutative semirings,
  from which the source statement follows.
* `eval₂Hom_sub_eval₂Hom_mem` and `dvd_eval₂Hom_sub_eval₂Hom` generalize the private
  `pow_dvd_eval₂Hom_sub_of_forall_pow_dvd_sub` of
  `ArkLib/Data/CodingTheory/ReedSolomon/HiddenDerivative/RootFinding/Regular/Iteration.lean`
  from a modulus `u ^ m` to any ideal or element, and from a ring `R` to a semiring.

* [Kopparty, S., *List-Decoding Multiplicity Codes*][Kop15], Theorem 4.4, uses this
  linearization with `I` generated by a power of `T - α`.
-/

@[expose] public section

namespace MvPolynomial

noncomputable section

variable {R S σ : Type*} [CommSemiring R]

section CommSemiring

variable [CommSemiring S]

/-- The linear term in the change of `p` under a perturbation `d`, evaluated at `a`:
`∑ i ∈ s, (∂p/∂xᵢ)(a) * dᵢ`.

The finite set `s` should contain the support of `d`. It may contain variables that do not occur
in `p`; their partial derivatives contribute zero. -/
def firstOrderIncrement (f : R →+* S) (a d : σ → S) (s : Finset σ)
    (p : MvPolynomial σ R) : S :=
  ∑ i ∈ s, eval₂Hom f a (pderiv i p) * d i

/-- The first-order increment is additive in the polynomial. -/
theorem firstOrderIncrement_add (f : R →+* S) (a d : σ → S) (s : Finset σ)
    (p q : MvPolynomial σ R) :
    firstOrderIncrement f a d s (p + q) =
      firstOrderIncrement f a d s p + firstOrderIncrement f a d s q := by
  simp [firstOrderIncrement, add_mul, Finset.sum_add_distrib]

/-- The increment of `p * X n` by the product rule. The second term uses only that `d`
vanishes outside `s`. -/
private theorem firstOrderIncrement_mul_X (f : R →+* S) (a d : σ → S) (s : Finset σ)
    (hd_zero : ∀ i, i ∉ s → d i = 0) (p : MvPolynomial σ R) (n : σ) :
    firstOrderIncrement f a d s (p * X n) =
      firstOrderIncrement f a d s p * a n + eval₂Hom f a p * d n := by
  classical
  have hsingle : ∑ i ∈ s, eval₂Hom f a p *
      eval₂Hom f a (if n = i then (1 : MvPolynomial σ R) else 0) * d i =
        eval₂Hom f a p * d n := by
    by_cases hn : n ∈ s
    · rw [Finset.sum_eq_single n]
      · simp
      · intro i _ hin
        simp [Ne.symm hin]
      · exact fun h ↦ absurd hn h
    · rw [Finset.sum_eq_zero, hd_zero n hn, mul_zero]
      intro i hi
      have hni : n ≠ i := fun h ↦ hn (h ▸ hi)
      simp [hni]
  simp only [firstOrderIncrement, pderiv_mul, map_add, map_mul, eval₂Hom_X', pderiv_X,
    Pi.single_apply, add_mul, Finset.sum_add_distrib, hsingle, Finset.sum_mul]
  congr 1
  exact Finset.sum_congr rfl fun i _ ↦ by ring

/-- First-order Taylor formula modulo `I ^ 2`, over commutative semirings. If `d` vanishes
outside the finite set `s` and each `d i` with `i ∈ s` lies in the ideal `I`, then
`p(a + d) = p(a) + ∑ i ∈ s, (∂p/∂xᵢ)(a) * dᵢ + e` for some `e ∈ I ^ 2`.

The hypothesis `hd_zero` is needed because the linear term only sums over `s`. -/
theorem exists_mem_sq_eval₂Hom_add_eq (f : R →+* S) (a d : σ → S) (s : Finset σ)
    (I : Ideal S) (p : MvPolynomial σ R) (hd : ∀ i ∈ s, d i ∈ I)
    (hd_zero : ∀ i, i ∉ s → d i = 0) :
    ∃ e ∈ I ^ 2,
      eval₂Hom f (a + d) p = eval₂Hom f a p + firstOrderIncrement f a d s p + e := by
  have hd_all (i : σ) : d i ∈ I := by
    by_cases hi : i ∈ s
    · exact hd i hi
    · simp [hd_zero i hi]
  induction p using MvPolynomial.induction_on with
  | C c => exact ⟨0, zero_mem _, by simp [firstOrderIncrement]⟩
  | add p q hp hq =>
    obtain ⟨e, he, hpe⟩ := hp
    obtain ⟨e', he', hqe⟩ := hq
    refine ⟨e + e', add_mem he he', ?_⟩
    rw [map_add, map_add, hpe, hqe, firstOrderIncrement_add]
    ring
  | mul_X p n hp =>
    obtain ⟨e, he, hpe⟩ := hp
    have hlinear : firstOrderIncrement f a d s p ∈ I :=
      I.sum_mem fun i _ ↦ I.mul_mem_left _ (hd_all i)
    refine ⟨firstOrderIncrement f a d s p * d n + e * (a n + d n),
      add_mem (by rw [pow_two]; exact Ideal.mul_mem_mul hlinear (hd_all n))
        ((I ^ 2).mul_mem_right _ he), ?_⟩
    rw [firstOrderIncrement_mul_X f a d s hd_zero, map_mul, map_mul, eval₂Hom_X',
      eval₂Hom_X', hpe, Pi.add_apply]
    ring

end CommSemiring

section CommRing

variable [CommRing S]

/-- First-order Taylor congruence: under the hypotheses of `exists_mem_sq_eval₂Hom_add_eq`,
`p(a + d) - p(a) - ∑ i ∈ s, (∂p/∂xᵢ)(a) * dᵢ ∈ I ^ 2`. -/
theorem eval₂Hom_add_sub_firstOrderIncrement_mem_sq (f : R →+* S) (a d : σ → S)
    (s : Finset σ) (I : Ideal S) (p : MvPolynomial σ R)
    (hd : ∀ i ∈ s, d i ∈ I) (hd_zero : ∀ i, i ∉ s → d i = 0) :
    eval₂Hom f (a + d) p - eval₂Hom f a p - firstOrderIncrement f a d s p ∈ I ^ 2 := by
  obtain ⟨e, he, heq⟩ := exists_mem_sq_eval₂Hom_add_eq f a d s I p hd hd_zero
  rw [heq]
  convert he using 1
  ring

/-- For finitely many variables the support set can be all variables, and `hd_zero` disappears. -/
theorem eval₂Hom_add_sub_firstOrderIncrement_univ_mem_sq [Fintype σ]
    (f : R →+* S) (a d : σ → S) (I : Ideal S) (p : MvPolynomial σ R)
    (hd : ∀ i, d i ∈ I) :
    eval₂Hom f (a + d) p - eval₂Hom f a p -
        firstOrderIncrement f a d Finset.univ p ∈ I ^ 2 :=
  eval₂Hom_add_sub_firstOrderIncrement_mem_sq f a d Finset.univ I p (fun i _ ↦ hd i)
    (fun i hi ↦ absurd (Finset.mem_univ i) hi)

/-- If every coordinate of `d` is divisible by `u ^ k` with `0 < k`, the first-order Taylor error
is divisible by `u ^ (k + 1)`.

The ideal statement gives divisibility by `u ^ (2 * k)`, which implies `u ^ (k + 1)` exactly when
`k ≥ 1`. For `k = 0` the conclusion fails in general: with `p = x ^ 2`, `a = 0`, `d = 1` and
`u = 0` over `ℤ`, the error is `1`. -/
theorem pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement (f : R →+* S) (a d : σ → S)
    (s : Finset σ) (p : MvPolynomial σ R) (u : S) (k : ℕ) (hk : 0 < k)
    (hd : ∀ i ∈ s, u ^ k ∣ d i) (hd_zero : ∀ i, i ∉ s → d i = 0) :
    u ^ (k + 1) ∣
      eval₂Hom f (a + d) p - eval₂Hom f a p - firstOrderIncrement f a d s p := by
  have hmem := eval₂Hom_add_sub_firstOrderIncrement_mem_sq f a d s
    (Ideal.span {u ^ k}) p (fun i hi ↦ Ideal.mem_span_singleton.mpr (hd i hi)) hd_zero
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton, ← pow_mul] at hmem
  exact (pow_dvd_pow u (by omega : k + 1 ≤ k * 2)).trans hmem

/-- Pivot form of `pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement`. If the pivot coordinate of
`d` is divisible by `u ^ k` and every other coordinate in `s` by `u ^ (k + 1)`, then modulo
`u ^ (k + 1)` the change `p(a + d) - p(a)` is `(∂p/∂x_pivot)(a) * d_pivot`. The hypothesis
`0 < k` is needed for the same reason as in `pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement`
(take `s = {pivot}`). -/
theorem pow_succ_dvd_eval₂Hom_add_sub_pderiv (f : R →+* S) (a d : σ → S)
    (s : Finset σ) (p : MvPolynomial σ R) (pivot : σ) (u : S) (k : ℕ) (hk : 0 < k)
    (hpivot : pivot ∈ s) (hd_pivot : u ^ k ∣ d pivot)
    (hd_other : ∀ i ∈ s, i ≠ pivot → u ^ (k + 1) ∣ d i)
    (hd_zero : ∀ i, i ∉ s → d i = 0) :
    u ^ (k + 1) ∣ eval₂Hom f (a + d) p - eval₂Hom f a p -
      eval₂Hom f a (pderiv pivot p) * d pivot := by
  classical
  have hd (i : σ) (hi : i ∈ s) : u ^ k ∣ d i := by
    by_cases hip : i = pivot
    · exact hip ▸ hd_pivot
    · exact (pow_dvd_pow u (Nat.le_succ k)).trans (hd_other i hi hip)
  have htaylor := pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement f a d s p u k hk hd hd_zero
  have hother : u ^ (k + 1) ∣ firstOrderIncrement f a d s p -
      eval₂Hom f a (pderiv pivot p) * d pivot := by
    rw [firstOrderIncrement, ← s.add_sum_erase _ hpivot, add_sub_cancel_left]
    refine Finset.dvd_sum fun i hi ↦ ?_
    have hi' := Finset.mem_erase.mp hi
    exact dvd_mul_of_dvd_right (hd_other i hi'.2 hi'.1) _
  convert htaylor.add hother using 1
  ring

/-- Zero-order congruence: if `a i - b i ∈ I` for every variable `i`, then
`p(a) - p(b) ∈ I`. -/
theorem eval₂Hom_sub_eval₂Hom_mem (f : R →+* S) (a b : σ → S) (I : Ideal S)
    (h : ∀ i, a i - b i ∈ I) (p : MvPolynomial σ R) :
    eval₂Hom f a p - eval₂Hom f b p ∈ I := by
  induction p using MvPolynomial.induction_on with
  | C c => simp
  | add p q hp hq =>
    convert I.add_mem hp hq using 1
    simp only [map_add]
    ring
  | mul_X p n hp =>
    convert I.add_mem (I.mul_mem_right (a n) hp) (I.mul_mem_left (eval₂Hom f b p) (h n)) using 1
    simp only [map_mul, eval₂Hom_X']
    ring

/-- Divisibility form of `eval₂Hom_sub_eval₂Hom_mem`: if `t ∣ a i - b i` for every variable `i`,
then `t ∣ p(a) - p(b)`. -/
theorem dvd_eval₂Hom_sub_eval₂Hom (f : R →+* S) (a b : σ → S) (t : S)
    (h : ∀ i, t ∣ a i - b i) (p : MvPolynomial σ R) :
    t ∣ eval₂Hom f a p - eval₂Hom f b p :=
  Ideal.mem_span_singleton.mp <| eval₂Hom_sub_eval₂Hom_mem f a b _
    (fun i ↦ Ideal.mem_span_singleton.mpr (h i)) p

end CommRing

end

end MvPolynomial
