name = "Arklib"
lintDriver = "batteries/runLinter"
defaultTargets = ["ArkLib"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longFile = 1500
weak.linter.style.header = false

[moreServerOptions]
linter.mathlibStandardSet = true
linter.style.longFile = 1500
linter.style.header = false

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCV-io"
rev = "v4.30.0"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.30.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.18.0"

[[require]]
name = "CompPoly"
git = "https://github.com/eliasjudin/CompPoly"
rev = "52a3ae4a979fe5a1d8425db05e37e9840802d850"

[[lean_lib]]
name = "ArkLib"
