/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import Mathlib.RingTheory.Ideal.GoingUp
public import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
public import Mathlib.RingTheory.Polynomial.RationalRoot
public import Mathlib.RingTheory.Ideal.UFD
public import Mathlib.RingTheory.IntegralClosure.GoingDown

/-!
# Height-one primes under an integral extension

Let `S` be an `R`-algebra and `P` a prime of `S`. If `S` has going down over `R`, the height of
`P.under R` is at most the height of `P`. If the extension is also integral and injective, a
nonzero prime of `S` contracts to a nonzero prime of `R`. Together these say that a height-one
prime contracts to a height-one prime when `R` is an integrally closed domain, `S` is a domain and
`S` is integral over `R`: Mathlib supplies going down in this situation. When `R` is moreover a
unique factorization domain, the contraction is generated by one prime element (Mathlib's
`UniqueFactorizationMonoid.isPrincipal_of_height_eq_one`). No Noetherian hypothesis is needed.

The motivating case is Noether normalization: an affine domain `A` over a field is finite over a
polynomial ring `B`, and a height-one prime of `A` contracts to a principal prime of `B`.

## Main statements

* `Ideal.height_under_le_height`: going down bounds the height of a contraction.
* `Ideal.height_under_eq_one`: a height-one prime contracts to a height-one prime along an
  injective integral extension of an integrally closed domain by a domain.
* `Ideal.exists_prime_under_eq_span_singleton`: over a unique factorization domain, the
  contraction is generated by a prime element.
-/

@[expose] public section

namespace Ideal

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]

/-- If `S` has going down over `R`, then `(P.under R).height ≤ P.height` for every prime `P` of
`S`: by going down, every chain of primes ending at `P.under R` lifts to a chain of the same
length ending at `P` (Mathlib's `Ideal.exists_ltSeries_of_hasGoingDown`).

Going down is needed: along the surjection `k[X, Y] → k[X, Y] ⧸ (X)`, the prime generated by the
class of `Y` has height one and contracts to `(X, Y)`, of height two. -/
theorem height_under_le_height [Algebra.HasGoingDown R S] (P : Ideal S) [P.IsPrime] :
    (P.under R).height ≤ P.height := by
  have hR := PrimeSpectrum.height_eq_orderHeight (⟨P.under R, inferInstance⟩ : PrimeSpectrum R)
  have hS := PrimeSpectrum.height_eq_orderHeight (⟨P, inferInstance⟩ : PrimeSpectrum S)
  dsimp only at hR hS
  rw [hR, hS]
  refine Order.height_le fun l hl ↦ ?_
  have : P.LiesOver l.last.asIdeal := ⟨by rw [hl]⟩
  obtain ⟨L, hlen, hlast, -⟩ := exists_ltSeries_of_hasGoingDown l P
  rw [← hlen]
  exact Order.length_le_height hlast.le

/-- Let `R` be integrally closed, `S` a domain, and `S` integral over `R` with
injective structure map. Then a prime of height one in `S` contracts to a prime of height one in
`R`.

The upper bound is `height_under_le_height`, with going down supplied by Mathlib for integral
extensions of an integrally closed domain by a domain; it fails without going down, as shown
there. The lower bound holds because the contraction of the nonzero prime `P` is strictly larger
than the contraction of `⊥`, which is `⊥` by injectivity. Integrality is needed for the lower
bound: the height-one prime `(Y)` of `k[X, Y]` contracts to `⊥` in `k[X]`. -/
theorem height_under_eq_one [IsDomain S] [FaithfulSMul R S]
    [Algebra.IsIntegral R S] [IsIntegrallyClosed R] (P : Ideal S) [P.IsPrime]
    (hP : P.height = 1) : (P.under R).height = 1 := by
  have : IsDomain R := (FaithfulSMul.algebraMap_injective R S).isDomain
  refine le_antisymm ((height_under_le_height P).trans hP.le) ?_
  rw [Order.one_le_iff_ne_zero, Ne, height_eq_zero_iff_eq_bot]
  intro h
  have hlt := IsIntegral.under_lt_under (R := R)
    (bot_lt_iff_ne_bot.mpr (ne_bot_of_height_eq_one hP))
  rw [under_bot, h] at hlt
  exact lt_irrefl _ hlt

/-- Let `R` be a unique factorization domain, `S` a domain, and `S` integral over `R`
with injective structure map. A prime of height one in `S` contracts to the ideal generated by a
prime element of `R`.

This is `height_under_eq_one` followed by Mathlib's
`UniqueFactorizationMonoid.isPrincipal_of_height_eq_one`; a generator of a nonzero prime principal
ideal is a prime element. -/
theorem exists_prime_under_eq_span_singleton [IsDomain R] [UniqueFactorizationMonoid R]
    [IsDomain S] [FaithfulSMul R S] [Algebra.IsIntegral R S]
    (P : Ideal S) [P.IsPrime] (hP : P.height = 1) :
    ∃ a : R, Prime a ∧ P.under R = span {a} := by
  have hheight := height_under_eq_one (R := R) P hP
  obtain ⟨a, ha⟩ := (UniqueFactorizationMonoid.isPrincipal_of_height_eq_one hheight).principal
  have ha' : P.under R = span {a} := ha.trans submodule_span_eq
  refine ⟨a, (span_singleton_prime ?_).mp (ha' ▸ inferInstance), ha'⟩
  rintro rfl
  exact ne_bot_of_height_eq_one hheight (ha'.trans (span_singleton_eq_bot.mpr rfl))

end Ideal
