/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import Mathlib.RingTheory.Ideal.Maps

/-!
# Prime ideals under surjective ring maps

A surjective ring map sends a prime ideal containing its kernel to a prime ideal. When the source
prime contains a principal cut by a lifted element, its image also records membership of that
cut and any finite family of lifted elements, together with avoidance of a chosen element.

## Main statements

* `Ideal.map_prime_principalOpenData_of_surjective`: transports a prime ideal, its comap, and
  principal open cut membership along a surjective ring map.

## References
-/

@[expose] public section

namespace Ideal

variable {R S : Type*} [CommRing R] [CommRing S]

/-- A surjective ring map transports a prime ideal and its principal open cut data.

If `Q` contains the sum of the kernel and the principal ideal generated by `gl`, then its image is
prime, has comap `Q`, contains the image of `gl` and the images of the lifted high cuts, and avoids
the image of `sl` whenever `Q` avoids `sl`. -/
theorem map_prime_principalOpenData_of_surjective
    (φ : R →+* S) (hφ : Function.Surjective φ) (Q : Ideal R) (hQ : Q.IsPrime)
    {g s : S} {gl sl : R}
    (hprincipal : RingHom.ker φ ⊔ Ideal.span {gl} ≤ Q)
    (hgl : φ gl = g) (hsl : φ sl = s) (hslQ : sl ∉ Q)
    (highCuts : List S) (highCutsLift : ∀ f, f ∈ highCuts → R)
    (hhighMap : ∀ f hf, φ (highCutsLift f hf) = f)
    (hhighLift : ∀ f hf, highCutsLift f hf ∈ Q) :
    (Q.map φ).IsPrime ∧ (Q.map φ).comap φ = Q ∧ s ∉ Q.map φ ∧ g ∈ Q.map φ ∧
      (∀ f ∈ highCuts, f ∈ Q.map φ) := by
  have hkerQ : RingHom.ker φ ≤ Q := le_sup_left.trans hprincipal
  have hglQ : gl ∈ Q := hprincipal
    ((le_sup_right : Ideal.span {gl} ≤ RingHom.ker φ ⊔ Ideal.span {gl})
      (Ideal.subset_span (Set.mem_singleton _)))
  have hprime : (Q.map φ).IsPrime :=
    @Ideal.map_isPrime_of_surjective R S (R →+* S) _ _ _ _ φ hφ Q hQ hkerQ
  have hcomap : (Q.map φ).comap φ = Q := by
    rw [Ideal.comap_map_of_surjective φ hφ Q]
    apply sup_eq_left.mpr
    rw [← RingHom.ker_eq_comap_bot]
    exact hkerQ
  refine ⟨hprime, hcomap, ?_, ?_, ?_⟩
  · intro hs
    apply hslQ
    have hsl' : sl ∈ (Q.map φ).comap φ := by
      change φ sl ∈ Q.map φ
      rw [hsl]
      exact hs
    rwa [hcomap] at hsl'
  · rw [← hgl]
    exact Ideal.mem_map_of_mem φ hglQ
  · intro f hf
    rw [← hhighMap f hf]
    exact Ideal.mem_map_of_mem φ (hhighLift f hf)

end Ideal
