/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.ToMathlib.RingTheory.Ideal.HeightUnder
public import ArkLib.ToMathlib.RingTheory.Ideal.PrincipalCut
public import ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineDegree
public import ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineHilbertAlgHom
public import ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineHilbertComponents
public import Mathlib.RingTheory.NoetherNormalization

/-!
# Purity and the Bézout bound for principal cuts of affine primes

Let `k` be a field, `σ` a finite type and `P` a prime ideal of `MvPolynomial σ k`. Write
`H(I)` for the affine Hilbert polynomial `affineHilbertPolynomial I`.

Noether normalization gives a finite injective `k`-algebra map
`g : MvPolynomial (Fin d) k →ₐ[k] MvPolynomial σ k ⧸ P`. Finite injective maps preserve the natural
degree of the affine Hilbert polynomial, so `natDegree H(P) = d`. If `J ⊇ P` is a prime whose
image in `MvPolynomial σ k ⧸ P` has height one, that image contracts along `g` to a height-one
prime of the unique factorization domain `MvPolynomial (Fin d) k`, which is generated by one prime
polynomial `a`. The induced map `MvPolynomial (Fin d) k ⧸ (a) → MvPolynomial σ k ⧸ J` is again
finite and injective, and a principal hypersurface in `d` variables has Hilbert polynomial of
natural degree `d - 1`. Hence `natDegree H(J) + 1 = natDegree H(P)`.

By Krull's principal ideal theorem every minimal prime `J` of a cut `P ⊔ span {f}` with `f ∉ P`
has height one modulo `P` (`Ideal.map_quotient_height_eq_one_of_mem_minimalPrimes_sup_span`), so
principal cuts of affine primes are pure: each component has dimension exactly one less. This
discharges the purity hypothesis of
`MvPolynomial.principalCut_sum_factorial_mul_leadingCoeff_minimalPrimes_le` and gives the Bézout
bound: if `totalDegree f ≤ b`, the affine degrees of the minimal primes of `P ⊔ span {f}` sum to at
most `b * affineDegree P`. Retaining only the components that avoid a fixed `s`, the potential
`affineDegree Q * b ^ natDegree H(Q)` does not increase under the cut.

Primality of `P` is used throughout: it makes the quotient a domain, which Noether normalization
and the height-one contraction need. Without it purity fails: for `P = (xy, xz)` in three
variables, the union of a plane and a line, and `f = x - 1`, which is regular modulo `P`, the only
component of the cut is the point `(1, 0, 0)`, of dimension `0` rather than `1`.

## Main statements

* `MvPolynomial.natDegree_affineHilbertPolynomial_eq_card_of_finite_of_injective`: a finite
  injective map from a polynomial ring in `τ` into the coordinate quotient forces
  `natDegree H(I) = Nat.card τ`.
* `MvPolynomial.natDegree_affineHilbertPolynomial_add_one_of_height_eq_one`: a prime of height one
  above an affine prime has Hilbert polynomial of natural degree one less.
* `MvPolynomial.principalCut_natDegree_affineHilbertPolynomial_add_one`: purity of principal cuts,
  and its hypersurface case
  `MvPolynomial.natDegree_affineHilbertPolynomial_add_one_of_mem_minimalPrimes_span_singleton`.
* `MvPolynomial.principalCut_sum_affineDegree_minimalPrimes_le`: the Bézout bound.
* `MvPolynomial.principalCut_sum_affineDegree_retainedMinimalPrimes_le`: the Bézout bound for the
  components retained by `s`.
* `MvPolynomial.sum_affineDegree_mul_pow_retainedMinimalPrimes_le`: the degree potential of the
  retained components of a cut.
* `MvPolynomial.sum_affineDegree_minimalPrimes_le`: the affine degrees of the minimal primes of an
  equidimensional ideal sum to at most its affine degree.
-/

@[expose] public section

noncomputable section

namespace MvPolynomial

variable {k σ : Type*} [Field k]

/-- If `g : MvPolynomial τ k →ₐ[k] MvPolynomial σ k ⧸ I` is finite and injective, the affine
Hilbert polynomial of `I` has natural degree `Nat.card τ`. This is
`natDegree_affineHilbertPolynomial_eq_of_finite_of_injective` applied to the zero ideal of
`MvPolynomial τ k`, whose Hilbert polynomial has natural degree `Nat.card τ`.

For a prime `I`, Noether normalization supplies such a `g` with `τ = Fin d`. Both hypotheses on
`g` are needed, as in `natDegree_affineHilbertPolynomial_eq_of_finite_of_injective`. -/
theorem natDegree_affineHilbertPolynomial_eq_card_of_finite_of_injective [Finite σ] {τ : Type*}
    [Finite τ] {I : Ideal (MvPolynomial σ k)} (g : MvPolynomial τ k →ₐ[k] MvPolynomial σ k ⧸ I)
    (hfin : g.Finite) (hinj : Function.Injective g) :
    (affineHilbertPolynomial I).natDegree = Nat.card τ := by
  let e := AlgEquiv.quotientBot k (MvPolynomial τ k)
  rw [natDegree_affineHilbertPolynomial_eq_of_finite_of_injective (g.comp e.toAlgHom)
    (RingHom.Finite.comp hfin e.toRingEquiv.finite) (hinj.comp e.injective),
    natDegree_affineHilbertPolynomial_bot]

/-- Let `P ≤ J` be primes of `MvPolynomial σ k` such that the image of `J` in
`MvPolynomial σ k ⧸ P` has height one. Then `natDegree H(J) + 1 = natDegree H(P)`.

Noether normalization gives a finite injective `g : MvPolynomial (Fin d) k →ₐ[k] A` with
`A = MvPolynomial σ k ⧸ P`, so `natDegree H(P) = d`. The image `Q` of `J` contracts to the ideal
of a prime polynomial `a` (`Ideal.exists_prime_under_eq_span_singleton`), and `g` induces a finite
injective map `MvPolynomial (Fin d) k ⧸ (a) → A ⧸ Q ≅ MvPolynomial σ k ⧸ J`. Since `a` is a
nonunit, `natDegree H((a)) + 1 = d`.

The proof uses that `J` is prime, so that the contraction of its image is a prime of the
polynomial ring. For a non-prime `J` the statement would follow from the fact that the natural
degree of `H(J)` is the largest natural degree over the minimal primes of `J`, which is not
formalized here. -/
theorem natDegree_affineHilbertPolynomial_add_one_of_height_eq_one [Finite σ]
    {P J : Ideal (MvPolynomial σ k)} [P.IsPrime] [J.IsPrime] (hPJ : P ≤ J)
    (hJ : (J.map (Ideal.Quotient.mk P)).height = 1) :
    (affineHilbertPolynomial J).natDegree + 1 = (affineHilbertPolynomial P).natDegree := by
  let A := MvPolynomial σ k ⧸ P
  let Q : Ideal A := J.map (Ideal.Quotient.mk P)
  have : Q.IsPrime := Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
    (by rwa [Ideal.mk_ker])
  obtain ⟨d, g, hg_inj, hg_fin⟩ := exists_finite_inj_algHom_of_fg k A
  let B := MvPolynomial (Fin d) k
  let _ : Algebra B A := g.toRingHom.toAlgebra
  have : Module.Finite B A := hg_fin
  have : FaithfulSMul B A := (faithfulSMul_iff_algebraMap_injective B A).mpr hg_inj
  obtain ⟨a, ha, hQa⟩ := Ideal.exists_prime_under_eq_span_singleton (R := B) Q hJ
  have hQa' : Q.comap g = Ideal.span {a} := hQa
  let e := DoubleQuot.quotQuotEquivQuotOfLEₐ k hPJ
  let child : (B ⧸ Ideal.span {a}) →ₐ[k] MvPolynomial σ k ⧸ J :=
    e.toAlgHom.comp (Ideal.quotientMapₐ Q g hQa'.ge)
  have hq : Function.Injective (Ideal.quotientMapₐ Q g hQa'.ge) :=
    Ideal.quotientMap_injective' (f := (g : B →+* A)) (H := hQa'.ge) hQa'.le
  have hchild_inj : Function.Injective child := e.injective.comp hq
  have hchild_fin : child.Finite := by
    refine AlgHom.Finite.of_comp_finite (f := Ideal.Quotient.mkₐ k (Ideal.span {a})) ?_
    have hcomp : child.comp (Ideal.Quotient.mkₐ k (Ideal.span {a})) =
        e.toAlgHom.comp ((Ideal.Quotient.mkₐ k Q).comp g) := by
      ext x
      rfl
    rw [hcomp]
    exact RingHom.Finite.comp e.toRingEquiv.finite
      (RingHom.Finite.comp (RingHom.Finite.of_surjective _ Ideal.Quotient.mk_surjective) hg_fin)
  have hparent := natDegree_affineHilbertPolynomial_eq_card_of_finite_of_injective g hg_fin hg_inj
  have hproper : Ideal.span {a} ≠ ⊤ := by
    rw [Ne, Ideal.span_singleton_eq_top]
    exact ha.not_isUnit
  rw [natDegree_affineHilbertPolynomial_eq_of_finite_of_injective child hchild_fin hchild_inj,
    natDegree_affineHilbertPolynomial_span_singleton_add_one ha.ne_zero hproper, hparent]

/-- Purity of principal cuts: if `P` is prime and `f ∉ P`, every minimal prime `J` of
`P ⊔ span {f}` satisfies `natDegree H(J) + 1 = natDegree H(P)`.

Krull's principal ideal theorem makes the image of `J` modulo `P` a prime of height one
(`Ideal.map_quotient_height_eq_one_of_mem_minimalPrimes_sup_span`), and
`natDegree_affineHilbertPolynomial_add_one_of_height_eq_one` applies. The hypothesis `f ∉ P` is
needed: for `f ∈ P` the only minimal prime is `P` itself. Primality of `P` is needed; see the
module docstring. -/
theorem principalCut_natDegree_affineHilbertPolynomial_add_one [Finite σ]
    {P J : Ideal (MvPolynomial σ k)} [P.IsPrime] {f : MvPolynomial σ k} (hf : f ∉ P)
    (hJ : J ∈ (P ⊔ Ideal.span {f}).minimalPrimes) :
    (affineHilbertPolynomial J).natDegree + 1 = (affineHilbertPolynomial P).natDegree :=
  have : J.IsPrime := hJ.isPrime
  natDegree_affineHilbertPolynomial_add_one_of_height_eq_one (le_sup_left.trans hJ.le)
    (Ideal.map_quotient_height_eq_one_of_mem_minimalPrimes_sup_span hf hJ)

/-- Every minimal prime `Q` over a nonzero principal ideal `span {g}` of `MvPolynomial σ k` has
`natDegree H(Q) + 1 = Nat.card σ`: the components of a hypersurface have codimension one.

This is `principalCut_natDegree_affineHilbertPolynomial_add_one` for `P = ⊥`. The hypothesis
`g ≠ 0` is needed: `span {0} = ⊥` is its own minimal prime, of natural degree `Nat.card σ`. -/
theorem natDegree_affineHilbertPolynomial_add_one_of_mem_minimalPrimes_span_singleton [Finite σ]
    {g : MvPolynomial σ k} (hg : g ≠ 0) {Q : Ideal (MvPolynomial σ k)}
    (hQ : Q ∈ (Ideal.span {g}).minimalPrimes) :
    (affineHilbertPolynomial Q).natDegree + 1 = Nat.card σ := by
  rw [← natDegree_affineHilbertPolynomial_bot (σ := σ) (k := k)]
  exact principalCut_natDegree_affineHilbertPolynomial_add_one (P := ⊥)
    (by rwa [Ideal.mem_bot]) (by rwa [bot_sup_eq])

/-- The Bézout bound for a principal cut of an affine prime: if `P` is prime, `f ∉ P` and
`totalDegree f ≤ b`, then the affine degrees of the minimal primes of `P ⊔ span {f}` sum to at
most `b * affineDegree P`.

This is `principalCut_sum_factorial_mul_leadingCoeff_minimalPrimes_le`, whose purity hypothesis is
`principalCut_natDegree_affineHilbertPolynomial_add_one`. A cut by a unit has no minimal primes,
and the sum is empty. The hypothesis `f ∉ P` is needed: for `P = ⊥` and `f = 0` the left side is
`affineDegree ⊥ = 1` while the right side is `0` for `b = 0`. -/
theorem principalCut_sum_affineDegree_minimalPrimes_le [Finite σ]
    {P : Ideal (MvPolynomial σ k)} [P.IsPrime] {f : MvPolynomial σ k} (hf : f ∉ P) {b : ℕ}
    (hfdeg : f.totalDegree ≤ b) :
    ∑ Q ∈ (P ⊔ Ideal.span {f}).minimalPrimesFinset, affineDegree Q ≤ b * affineDegree P := by
  have hpure : ∀ Q ∈ (P ⊔ Ideal.span {f}).minimalPrimesFinset,
      (affineHilbertPolynomial Q).natDegree = (affineHilbertPolynomial P).natDegree - 1 :=
    fun Q hQ ↦ by
      have := principalCut_natDegree_affineHilbertPolynomial_add_one hf
        (Ideal.mem_minimalPrimesFinset.mp hQ)
      omega
  have hreg : IsLeftRegular (Ideal.Quotient.mk P f) := by
    intro x y hxy
    exact mul_left_cancel₀ (fun h ↦ hf (Ideal.Quotient.eq_zero_iff_mem.mp h)) hxy
  calc ∑ Q ∈ (P ⊔ Ideal.span {f}).minimalPrimesFinset, affineDegree Q
      = ∑ Q ∈ (P ⊔ Ideal.span {f}).minimalPrimesFinset,
          (((affineHilbertPolynomial P).natDegree - 1).factorial : ℚ) *
            (affineHilbertPolynomial Q).leadingCoeff :=
        Finset.sum_congr rfl fun Q hQ ↦ by rw [affineDegree, hpure Q hQ]
    _ ≤ (b : ℚ) * ((affineHilbertPolynomial P).natDegree.factorial : ℚ) *
          (affineHilbertPolynomial P).leadingCoeff :=
        principalCut_sum_factorial_mul_leadingCoeff_minimalPrimes_le hreg hfdeg hpure
    _ = b * affineDegree P := by rw [affineDegree, mul_assoc]

/-- The Bézout bound for the retained components of a principal cut: if `P` is prime, `f ∉ P` and
`totalDegree f ≤ b`, the affine degrees of the minimal primes of `P ⊔ span {f}` that do not contain
`s` sum to at most `b * affineDegree P`.

Dropping components only decreases the sum, since affine degrees are nonnegative, so this follows
from `principalCut_sum_affineDegree_minimalPrimes_le`. No hypothesis on `s` is needed. The
hypothesis `f ∉ P` is needed for the reason given there. -/
theorem principalCut_sum_affineDegree_retainedMinimalPrimes_le [Finite σ]
    {P : Ideal (MvPolynomial σ k)} [P.IsPrime] (s : MvPolynomial σ k) {f : MvPolynomial σ k}
    (hf : f ∉ P) {b : ℕ} (hfdeg : f.totalDegree ≤ b) :
    ∑ Q ∈ (P ⊔ Ideal.span {f}).retainedMinimalPrimes s, affineDegree Q ≤ b * affineDegree P :=
  (Finset.sum_le_sum_of_subset_of_nonneg (Ideal.retainedMinimalPrimes_subset _ s)
      fun Q _ _ ↦ affineDegree_nonneg Q).trans
    (principalCut_sum_affineDegree_minimalPrimes_le hf hfdeg)

/-- The degree potential does not increase under a retained principal cut. Let `P` be prime and
`totalDegree f ≤ b`. Summing `affineDegree Q * b ^ natDegree H(Q)` over the minimal primes `Q` of
`P ⊔ span {f}` that do not contain `s` gives at most `affineDegree P * b ^ natDegree H(P)`.

If `f ∈ P`, the cut is `P` and the retained family is `{P}` or empty. Otherwise every retained
component has natural degree `natDegree H(P) - 1` by purity, and the Bézout bound
`principalCut_sum_affineDegree_minimalPrimes_le` supplies the factor `b`; if `natDegree H(P) = 0`
purity leaves no component. No hypothesis on `s` or on `b` is needed. -/
theorem sum_affineDegree_mul_pow_retainedMinimalPrimes_le [Finite σ]
    {P : Ideal (MvPolynomial σ k)} [P.IsPrime] (s : MvPolynomial σ k) {f : MvPolynomial σ k}
    {b : ℕ} (hfdeg : f.totalDegree ≤ b) :
    ∑ Q ∈ (P ⊔ Ideal.span {f}).retainedMinimalPrimes s,
        affineDegree Q * (b : ℚ) ^ (affineHilbertPolynomial Q).natDegree ≤
      affineDegree P * (b : ℚ) ^ (affineHilbertPolynomial P).natDegree := by
  classical
  by_cases hf : f ∈ P
  · refine (Finset.sum_le_sum_of_subset_of_nonneg (t := {P}) ?_ fun Q _ _ ↦
      mul_nonneg (affineDegree_nonneg Q) (by positivity)).trans_eq (Finset.sum_singleton _ _)
    intro Q hQ
    rw [sup_eq_left.mpr ((Ideal.span_singleton_le_iff_mem P).mpr hf)] at hQ
    have hmin := (Ideal.mem_retainedMinimalPrimes.mp hQ).1
    rw [Ideal.minimalPrimes_eq_subsingleton_self] at hmin
    exact Finset.mem_singleton.mpr hmin
  set d := (affineHilbertPolynomial P).natDegree
  have hchild : ∀ Q ∈ (P ⊔ Ideal.span {f}).retainedMinimalPrimes s,
      (affineHilbertPolynomial Q).natDegree + 1 = d := fun Q hQ ↦
    principalCut_natDegree_affineHilbertPolynomial_add_one hf
      (Ideal.mem_retainedMinimalPrimes.mp hQ).1
  have hsum := principalCut_sum_affineDegree_retainedMinimalPrimes_le s hf hfdeg
  rcases Nat.eq_zero_or_pos d with hd | hd
  · rw [Finset.sum_eq_zero fun Q hQ ↦ by have := hchild Q hQ; omega]
    exact mul_nonneg (affineDegree_nonneg P) (by positivity)
  calc ∑ Q ∈ (P ⊔ Ideal.span {f}).retainedMinimalPrimes s,
        affineDegree Q * (b : ℚ) ^ (affineHilbertPolynomial Q).natDegree
      = (∑ Q ∈ (P ⊔ Ideal.span {f}).retainedMinimalPrimes s, affineDegree Q) *
          (b : ℚ) ^ (d - 1) := by
        rw [Finset.sum_mul]
        exact Finset.sum_congr rfl fun Q hQ ↦ by
          rw [show (affineHilbertPolynomial Q).natDegree = d - 1 by have := hchild Q hQ; omega]
    _ ≤ (b * affineDegree P) * (b : ℚ) ^ (d - 1) :=
        mul_le_mul_of_nonneg_right hsum (by positivity)
    _ = affineDegree P * (b : ℚ) ^ d := by
        rw [mul_comm (b : ℚ), mul_assoc, ← pow_succ', Nat.sub_add_cancel hd]

/-- The affine degrees of the minimal primes `Q` over `I` whose affine Hilbert polynomial has the
same natural degree `d` as that of `I` sum to at most `affineDegree I`.

Each such `Q` has affine degree `d! * coeff d H(Q)`. The coefficient in degree `d` is nonnegative
for every minimal prime, since `natDegree H(Q) ≤ d`, so adding the remaining minimal primes does
not decrease the sum, and `sum_coeff_affineHilbertPolynomial_minimalPrimes_le` bounds the sum over
all minimal primes by `coeff d H(I)`. -/
theorem sum_affineDegree_minimalPrimes_filter_le [Finite σ] (I : Ideal (MvPolynomial σ k)) :
    ∑ Q ∈ I.minimalPrimesFinset with
        (affineHilbertPolynomial Q).natDegree = (affineHilbertPolynomial I).natDegree,
      affineDegree Q ≤ affineDegree I := by
  set d := (affineHilbertPolynomial I).natDegree with hd
  have hdeg : ∀ Q ∈ I.minimalPrimesFinset, (affineHilbertPolynomial Q).natDegree ≤ d :=
    fun Q hQ ↦ natDegree_affineHilbertPolynomial_le_of_le (Ideal.mem_minimalPrimesFinset.mp hQ).1.2
  calc ∑ Q ∈ I.minimalPrimesFinset with (affineHilbertPolynomial Q).natDegree = d,
        affineDegree Q
      = (d.factorial : ℚ) * ∑ Q ∈ I.minimalPrimesFinset with
          (affineHilbertPolynomial Q).natDegree = d, (affineHilbertPolynomial Q).coeff d := by
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl fun Q hQ ↦ ?_
        have hQd := (Finset.mem_filter.mp hQ).2
        rw [affineDegree, hQd, Polynomial.leadingCoeff, hQd]
    _ ≤ (d.factorial : ℚ) * ∑ Q ∈ I.minimalPrimesFinset, (affineHilbertPolynomial Q).coeff d :=
        mul_le_mul_of_nonneg_left (Finset.sum_le_sum_of_subset_of_nonneg
          (Finset.filter_subset _ _) fun Q hQ _ ↦
            Polynomial.coeff_nonneg_of_natDegree_le_of_eventually_eval_natCast_nonneg (hdeg Q hQ)
              (eventually_eval_affineHilbertPolynomial_nonneg Q)) (Nat.cast_nonneg _)
    _ ≤ (d.factorial : ℚ) * (affineHilbertPolynomial I).coeff d :=
        mul_le_mul_of_nonneg_left (sum_coeff_affineHilbertPolynomial_minimalPrimes_le I le_rfl)
          (Nat.cast_nonneg _)
    _ = affineDegree I := by rw [affineDegree, Polynomial.leadingCoeff]

/-- For an equidimensional ideal `I`, whose minimal primes all have affine Hilbert polynomials of
the same natural degree as that of `I`, the affine degrees of the minimal primes sum to at most
`affineDegree I`.

This is `sum_affineDegree_minimalPrimes_filter_le`, whose filter keeps every minimal prime. The
hypothesis is needed: for `I = span {X₀ * X₁, X₀ * X₂}` in three variables, the union of the plane
`X₀ = 0` and the line `X₁ = X₂ = 0`, the line has affine degree `1` and does not count towards the
leading coefficient of the Hilbert polynomial of `I`, which is that of the plane. -/
theorem sum_affineDegree_minimalPrimes_le [Finite σ] {I : Ideal (MvPolynomial σ k)}
    (hpure : ∀ Q ∈ I.minimalPrimesFinset,
      (affineHilbertPolynomial Q).natDegree = (affineHilbertPolynomial I).natDegree) :
    ∑ Q ∈ I.minimalPrimesFinset, affineDegree Q ≤ affineDegree I := by
  have h := sum_affineDegree_minimalPrimes_filter_le I
  rwa [Finset.filter_true_of_mem hpure] at h

end MvPolynomial
