/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.ToMathlib.LinearAlgebra.Matrix.InvertibleCombination
public import ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineHilbertAlgHom
public import Mathlib.Algebra.MvPolynomial.Supported
public import Mathlib.RingTheory.Adjoin.Polynomial.Basic

/-!
# Affine Hilbert dimension of coefficient-evaluation equations

Let `k` be a field, `σ` a finite type and `I` an ideal of `MvPolynomial σ k`. Write `P_I` for
`affineHilbertPolynomial I`; its natural degree is the dimension of the zero locus of `I`.

Suppose `I` contains `c` polynomials `p i` that, modulo polynomials in the variables outside
`v : ι ↪ σ`, are the rows `∑ j, A i j • X (v j)` of a matrix `A` with invertible determinant. In
`MvPolynomial σ k ⧸ I` the classes of the variables `X (v j)` are then combinations of elements of
the subalgebra generated by the other variables, so these other variables generate the quotient,
and `natDegree P_I ≤ Nat.card σ - Fintype.card ι`. No primality or properness of `I` is needed.

The main application is to the coefficients of a polynomial of degree less than `m`. Its
coefficients are variables `X (v l)` for `l < m`, and the equation stating that its value at
`α` is `r`, where `r` is a polynomial in the other variables, is
`∑ l, α ^ l * X (v l) - r`. The equations at `c ≤ m` distinct points form a Vandermonde system
in the first `c` coefficients, so an ideal containing them has
`natDegree P_I ≤ Nat.card σ - c`. There are two named instances:

* `fixedCoefficientEvaluation m α y`, in the `m` coefficient variables, states that the value at
  `α` is the constant `y`; an ideal containing `c` of these at distinct points has dimension at
  most `m - c`.
* `polynomialCoefficientEvaluation m α received`, in the coefficient variables and one further
  variable `z = X none`, states that the value at `α` is `received(z)`; an ideal containing
  `c ≤ m` of these at distinct points has dimension at most `m + 1 - c`. The special case
  `received = f + z * g` is `affineCoefficientEvaluation m α f g`.

For the fixed equations, a positive-dimensional ideal `P` contains at most `m - natDegree P_P`
of the equations at distinct points `α i`: if `c` of them lie in `P`, then
`natDegree P_P ≤ m - c`, and positive dimension forces `c < m`.

## Main statements

* `MvPolynomial.natDegree_affineHilbertPolynomial_le_card_sub_of_isUnit_det`: elimination of
  variables by an invertible linear system.
* `MvPolynomial.natDegree_affineHilbertPolynomial_le_card_sub_of_sum_pow_mul_X_sub_mem`:
  elimination of coefficients by evaluations at distinct points.
* `MvPolynomial.natDegree_affineHilbertPolynomial_le_of_fixedCoefficientEvaluation_mem`,
  `MvPolynomial.natDegree_affineHilbertPolynomial_le_of_polynomialCoefficientEvaluation_mem`,
  `MvPolynomial.natDegree_affineHilbertPolynomial_le_of_affineCoefficientEvaluation_mem`: the
  named instances.
* `MvPolynomial.natDegree_affineHilbertPolynomial_add_ncard_le_of_fixedCoefficientEvaluation`:
  a positive-dimensional ideal contains at most `m - natDegree P_P` fixed evaluation equations at
  distinct points.
* `MvPolynomial.natDegree_affineHilbertPolynomial_add_ncard_le_of_polynomialCoefficientEvaluation`:
  an ideal of dimension greater than one has an affine dimension bound from any finite set of
  polynomial evaluation equations it contains.
-/

@[expose] public section

noncomputable section

open scoped Finset

namespace MvPolynomial

variable {k σ ι : Type*} [Field k]

/-- **Elimination by an invertible linear system.** Let `v : ι ↪ σ` and let `A` be a square
matrix over `k` with invertible determinant. If `I` contains polynomials `p i` such that each
`p i - ∑ j, A i j • X (v j)` involves only variables outside the range of `v`, then the classes of
those other variables generate `MvPolynomial σ k ⧸ I`, so the affine Hilbert polynomial of `I`
has natural degree at most `Nat.card σ - Fintype.card ι`. -/
theorem natDegree_affineHilbertPolynomial_le_card_sub_of_isUnit_det [Finite σ] [Fintype ι]
    [DecidableEq ι] {I : Ideal (MvPolynomial σ k)} (v : ι ↪ σ) (A : Matrix ι ι k)
    (hA : IsUnit A.det) (p : ι → MvPolynomial σ k) (hpI : ∀ i, p i ∈ I)
    (hp : ∀ i, p i - ∑ j, A i j • X (v j) ∈ supported k (Set.range v)ᶜ) :
    (affineHilbertPolynomial I).natDegree ≤ Nat.card σ - Fintype.card ι := by
  classical
  let q := Ideal.Quotient.mkₐ k I
  let x : ↥(Set.range v)ᶜ → MvPolynomial σ k ⧸ I := fun i ↦ q (X i.1)
  let B := Algebra.adjoin k (Set.range x)
  have hsupp : ∀ f ∈ supported k (Set.range v)ᶜ, q f ∈ B := by
    intro f hf
    have hmap : q f ∈ (supported k (Set.range v)ᶜ).map q := Subalgebra.mem_map.mpr ⟨f, hf, rfl⟩
    rwa [supported_eq_adjoin_X, AlgHom.map_adjoin, Set.image_image, Set.image_eq_range] at hmap
  have hvar : ∀ j, q (X (v j)) ∈ B := by
    refine Submodule.mem_of_forall_sum_smul_mem (p := Subalgebra.toSubmodule B) A hA
      (x := fun j ↦ q (X (v j))) fun i ↦ ?_
    have h := B.neg_mem (hsupp _ (hp i))
    rwa [map_sub, show q (p i) = 0 from Ideal.Quotient.eq_zero_iff_mem.mpr (hpI i), zero_sub,
      neg_neg, map_sum] at h
  have hall (f : MvPolynomial σ k) : q f ∈ B := by
    induction f using MvPolynomial.induction_on with
    | C a => simpa only [← algebraMap_eq, AlgHom.commutes] using B.algebraMap_mem a
    | add f g hf hg => simpa only [map_add] using B.add_mem hf hg
    | mul_X f i hf =>
      rw [map_mul]
      refine B.mul_mem hf ?_
      by_cases hi : i ∈ Set.range v
      · obtain ⟨j, rfl⟩ := hi
        exact hvar j
      · exact Algebra.subset_adjoin ⟨⟨i, hi⟩, rfl⟩
  have htop : B = ⊤ := eq_top_iff.mpr fun y _ ↦ by
    obtain ⟨f, rfl⟩ := Ideal.Quotient.mkₐ_surjective k I y
    exact hall f
  have hdim := natDegree_affineHilbertPolynomial_le_card_of_adjoin_eq_top x htop
  rwa [Nat.card_coe_set_eq, Set.ncard_compl, Set.ncard_range_of_injective v.injective,
    Nat.card_eq_fintype_card (α := ι)] at hdim

/-- **Elimination of coefficients by evaluations.** Let the variables `X (v l)`, `l < m`, be the
coefficients of a polynomial of degree less than `m`, and let `c ≤ m`. If `I` contains, for `c`
distinct points `α i`, an equation `∑ l, α i ^ l * X (v l) - r i` whose value `r i` involves only
variables outside the range of `v`, then the affine Hilbert polynomial of `I` has natural degree at
most `Nat.card σ - c`: the equations form a Vandermonde system in the first `c` coefficients. -/
theorem natDegree_affineHilbertPolynomial_le_card_sub_of_sum_pow_mul_X_sub_mem [Finite σ]
    {I : Ideal (MvPolynomial σ k)} {m c : ℕ} (hcm : c ≤ m) (v : Fin m ↪ σ) (α : Fin c ↪ k)
    (r : Fin c → MvPolynomial σ k) (hr : ∀ i, r i ∈ supported k (Set.range v)ᶜ)
    (hI : ∀ i, (∑ l : Fin m, C (α i ^ (l : ℕ)) * X (v l)) - r i ∈ I) :
    (affineHilbertPolynomial I).natDegree ≤ Nat.card σ - c := by
  classical
  let w : Fin c ↪ σ := (Fin.castLEEmb hcm).trans v
  have hw : Set.range w ⊆ Set.range v := fun _ ⟨j, hj⟩ ↦ ⟨_, hj⟩
  have hdim := natDegree_affineHilbertPolynomial_le_card_sub_of_isUnit_det w
    (Matrix.vandermonde fun i ↦ α i)
    (isUnit_iff_ne_zero.mpr (Matrix.det_vandermonde_ne_zero_iff.mpr α.injective)) _ hI
    fun i ↦ ?_
  · rwa [Fintype.card_fin] at hdim
  have hsplit := Finset.sum_sdiff (f := fun l : Fin m ↦ C (α i ^ (l : ℕ)) * X (v l))
    (Finset.subset_univ (Finset.univ.map (Fin.castLEEmb hcm)))
  rw [Finset.sum_map] at hsplit
  rw [← hsplit, sub_right_comm, add_sub_assoc]
  refine Subalgebra.sub_mem _ (Subalgebra.add_mem _ (Subalgebra.sum_mem _ fun l hl ↦ ?_) ?_)
    (supported_mono (Set.compl_subset_compl.mpr hw) (hr i))
  · refine Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ (α i ^ (l : ℕ)))
      (X_mem_supported.mpr ?_)
    rintro ⟨j, hj⟩
    refine (Finset.mem_sdiff.mp hl).2 (Finset.mem_map.mpr ⟨j, Finset.mem_univ _, ?_⟩)
    exact v.injective hj
  · convert (supported k (Set.range w)ᶜ).zero_mem using 1
    rw [sub_eq_zero]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [Matrix.vandermonde_apply, C_mul']
    rfl

/-- The equation stating that the polynomial of degree less than `m` with coefficient variables
`X l` takes the value `y` at `α`: `∑ l, α ^ l * X l - y`. -/
def fixedCoefficientEvaluation (m : ℕ) (α y : k) : MvPolynomial (Fin m) k :=
  (∑ l : Fin m, C (α ^ (l : ℕ)) * X l) - C y

/-- The equation stating that the polynomial of degree less than `m` with coefficient variables
`X (some l)` takes the value `received(z)` at `α`, where `z = X none`:
`∑ l, α ^ l * X (some l) - received(z)`. -/
def polynomialCoefficientEvaluation (m : ℕ) (α : k) (received : Polynomial k) :
    MvPolynomial (Option (Fin m)) k :=
  (∑ l : Fin m, C (α ^ (l : ℕ)) * X (some l)) - received.eval₂ C (X none)

/-- The special case `received = f + z * g` of `polynomialCoefficientEvaluation`. -/
def affineCoefficientEvaluation (m : ℕ) (α f g : k) : MvPolynomial (Option (Fin m)) k :=
  polynomialCoefficientEvaluation m α (Polynomial.C f + Polynomial.X * Polynomial.C g)

/-- The fixed coefficient evaluation equation has total degree at most one. -/
theorem totalDegree_fixedCoefficientEvaluation_le (m : ℕ) (α y : k) :
    (fixedCoefficientEvaluation m α y).totalDegree ≤ 1 := by
  refine (totalDegree_sub _ _).trans (max_le ((totalDegree_finsetSum _ _).trans ?_) (by simp))
  refine Finset.sup_le fun l _ ↦ (totalDegree_mul _ _).trans ?_
  rw [totalDegree_C, totalDegree_X]

/-- An ideal of `MvPolynomial (Fin m) k` containing the fixed evaluation equations at `c`
distinct points has affine Hilbert polynomial of natural degree at most `m - c`. For `c ≥ m` the
bound is zero: the first `m` equations already determine the coefficients. -/
theorem natDegree_affineHilbertPolynomial_le_of_fixedCoefficientEvaluation_mem {m c : ℕ}
    (α : Fin c ↪ k) (y : Fin c → k) {I : Ideal (MvPolynomial (Fin m) k)}
    (hI : ∀ i, fixedCoefficientEvaluation m (α i) (y i) ∈ I) :
    (affineHilbertPolynomial I).natDegree ≤ m - c := by
  have hle {c' : ℕ} (hc' : c' ≤ m) (β : Fin c' ↪ k) (z : Fin c' → k)
      (hz : ∀ i, fixedCoefficientEvaluation m (β i) (z i) ∈ I) :
      (affineHilbertPolynomial I).natDegree ≤ m - c' := by
    have h := natDegree_affineHilbertPolynomial_le_card_sub_of_sum_pow_mul_X_sub_mem hc'
      (Function.Embedding.refl _) β (fun i ↦ C (z i))
      (fun i ↦ Subalgebra.algebraMap_mem _ (z i)) hz
    rwa [Nat.card_eq_fintype_card, Fintype.card_fin] at h
  by_cases hcm : c ≤ m
  · exact hle hcm α y hI
  · have h := hle le_rfl ((Fin.castLEEmb (by omega : m ≤ c)).trans α)
      (fun i ↦ y (Fin.castLEEmb (by omega : m ≤ c) i)) fun i ↦ hI _
    omega

/-- An ideal of `MvPolynomial (Option (Fin m)) k` containing the polynomial evaluation equations
at `c ≤ m` distinct points has affine Hilbert polynomial of natural degree at most `m + 1 - c`. -/
theorem natDegree_affineHilbertPolynomial_le_of_polynomialCoefficientEvaluation_mem {m c : ℕ}
    (hcm : c ≤ m) (α : Fin c ↪ k) (received : Fin c → Polynomial k)
    {I : Ideal (MvPolynomial (Option (Fin m)) k)}
    (hI : ∀ i, polynomialCoefficientEvaluation m (α i) (received i) ∈ I) :
    (affineHilbertPolynomial I).natDegree ≤ m + 1 - c := by
  have hz : X none ∈ supported k (Set.range (Function.Embedding.some : Fin m ↪ Option (Fin m)))ᶜ :=
    X_mem_supported.mpr fun ⟨_, h⟩ ↦ Option.some_ne_none _ h
  have h := natDegree_affineHilbertPolynomial_le_card_sub_of_sum_pow_mul_X_sub_mem hcm
    Function.Embedding.some α (fun i ↦ (received i).eval₂ C (X none))
    (fun i ↦ by
      rw [← algebraMap_eq, ← Polynomial.aeval_def]
      exact Algebra.adjoin_le (Set.singleton_subset_iff.mpr hz)
        (Polynomial.aeval_mem_adjoin_singleton k _)) hI
  rwa [Nat.card_eq_fintype_card, Fintype.card_option, Fintype.card_fin] at h

/-- On an ideal of dimension greater than one, the dimension and the number of polynomial
evaluation equations it contains add up to at most `m + 1`. -/
theorem natDegree_affineHilbertPolynomial_add_ncard_le_of_polynomialCoefficientEvaluation
    {n m : ℕ} (α : Fin n ↪ k) (received : Fin n → Polynomial k)
    {I : Ideal (MvPolynomial (Option (Fin m)) k)}
    (S : Set (Fin n))
    (hI : ∀ i ∈ S, polynomialCoefficientEvaluation m (α i) (received i) ∈ I)
    (hd : 1 < (affineHilbertPolynomial I).natDegree) :
    (affineHilbertPolynomial I).natDegree +
        S.ncard ≤ m + 1 := by
  classical
  let hSfin : S.Finite := Set.toFinite S
  let bad := hSfin.toFinset
  have hbad : S.ncard = bad.card := by
    simpa [bad] using Set.ncard_eq_toFinset_card S hSfin
  by_cases hcount : bad.card ≤ m
  · let e := (bad.orderEmbOfFin rfl).toEmbedding
    have hdegree := natDegree_affineHilbertPolynomial_le_of_polynomialCoefficientEvaluation_mem
      hcount (e.trans α) (fun j ↦ received (e j)) fun j ↦
        hI (e j) (hSfin.mem_toFinset.mp (bad.orderEmbOfFin_mem rfl j))
    rw [hbad]
    omega
  · have hm : m ≤ bad.card := by omega
    obtain ⟨indices, hsubset, hcard⟩ := Finset.exists_subset_card_eq hm
    let e : Fin m ↪ Fin n := (indices.orderEmbOfFin hcard).toEmbedding
    have hmem (j : Fin m) :
        polynomialCoefficientEvaluation m (α (e j)) (received (e j)) ∈ I := by
      have hj : e j ∈ bad := hsubset (indices.orderEmbOfFin_mem hcard j)
      exact hI (e j) (hSfin.mem_toFinset.mp hj)
    have hdegree := natDegree_affineHilbertPolynomial_le_of_polynomialCoefficientEvaluation_mem
      le_rfl (e.trans α) (fun j ↦ received (e j)) hmem
    omega

/-- An ideal of `MvPolynomial (Option (Fin m)) k` containing the affine evaluation equations at
`c ≤ m` distinct points has affine Hilbert polynomial of natural degree at most `m + 1 - c`. -/
theorem natDegree_affineHilbertPolynomial_le_of_affineCoefficientEvaluation_mem {m c : ℕ}
    (hcm : c ≤ m) (α : Fin c ↪ k) (f g : Fin c → k)
    {I : Ideal (MvPolynomial (Option (Fin m)) k)}
    (hI : ∀ i, affineCoefficientEvaluation m (α i) (f i) (g i) ∈ I) :
    (affineHilbertPolynomial I).natDegree ≤ m + 1 - c :=
  natDegree_affineHilbertPolynomial_le_of_polynomialCoefficientEvaluation_mem hcm α _ hI

/-- **Evaluation equations on a positive-dimensional ideal.** Let `α i`, `i < n`, be distinct
points. An ideal `P` of `MvPolynomial (Fin m) k` of positive dimension contains at most
`m - natDegree P_P` of the fixed evaluation equations at the points `α i`; equivalently, the
dimension and the number of these equations in `P` add up to at most `m`.

The equations in `P` give `natDegree P_P ≤ m - c`, where `c` is their number, and positive
dimension forces `c < m`. The hypothesis of positive dimension is needed: the unit ideal contains
all `n` equations, and `n` may exceed `m`. -/
theorem natDegree_affineHilbertPolynomial_add_ncard_le_of_fixedCoefficientEvaluation {n m : ℕ}
    (α : Fin n ↪ k) (y : Fin n → k) {P : Ideal (MvPolynomial (Fin m) k)}
    (hP : 0 < (affineHilbertPolynomial P).natDegree) :
    (affineHilbertPolynomial P).natDegree +
        {i | fixedCoefficientEvaluation m (α i) (y i) ∈ P}.ncard ≤ m := by
  classical
  set bad := Finset.univ.filter fun i ↦ fixedCoefficientEvaluation m (α i) (y i) ∈ P
  have hbad : {i | fixedCoefficientEvaluation m (α i) (y i) ∈ P}.ncard = #bad := by
    rw [← Set.ncard_coe_finset, Finset.coe_filter]
    simp
  let e := (bad.orderEmbOfFin rfl).toEmbedding
  have h := natDegree_affineHilbertPolynomial_le_of_fixedCoefficientEvaluation_mem (e.trans α)
    (fun j ↦ y (e j)) fun j ↦ (Finset.mem_filter.mp (bad.orderEmbOfFin_mem rfl j)).2
  rw [hbad]
  omega

end MvPolynomial
