/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.ToMathlib.Combinatorics.Enumerative.MonomialCount
public import ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineHilbert
public import Mathlib.Data.Finsupp.PWO
public import Mathlib.RingTheory.MvPolynomial.Groebner
public import Mathlib.RingTheory.MvPolynomial.MonomialOrder.DegLex

/-!
# Standard monomials and the affine Hilbert function

Fix a monomial order `m` on `σ →₀ ℕ` and an ideal `I` of `MvPolynomial σ k` over a field `k`.
An exponent vector is *standard* for `I` if it is not divisible by the leading exponent
`m.degree p` of any nonzero `p ∈ I`. The standard exponents form a lower set, and the polynomials
supported on them form the subspace `MonomialOrder.standardSpace m I`.

Division by the nonzero elements of `I` (Mathlib's `MonomialOrder.div_set`) gives every
polynomial a standard representative modulo `I` whose leading exponent is no larger. A nonzero
standard polynomial cannot lie in `I`, because its leading exponent would be divisible by itself.
Hence the quotient map restricts to a linear equivalence from the standard space onto
`MvPolynomial σ k ⧸ I`.

If `m` is graded, meaning that `a ≼[m] b` implies `degree a ≤ degree b` (as for
`MonomialOrder.degLex`), then the representative has no larger total degree, and the equivalence
restricts to the total-degree filtration. Consequently the affine Hilbert function counts the
standard exponents of degree at most `N`. With finitely many variables, Dickson's lemma makes the
non-standard exponents the union of finitely many cones, and the count in
`ArkLib.ToMathlib.Combinatorics.Enumerative.MonomialCount` shows that the affine Hilbert function
agrees, for all large `N`, with a polynomial of degree at most the number of variables.

The polynomial itself, `MvPolynomial.affineHilbertPolynomial`, is defined in
`ArkLib.ToMathlib.RingTheory.MvPolynomial.AffineHilbertPolynomial`.

## Main statements

* `MonomialOrder.standardExponents`, `MonomialOrder.standardSpace`: the standard exponents and the
  polynomials supported on them.
* `MonomialOrder.standardQuotientEquiv`: every quotient class has exactly one standard
  representative.
* `MonomialOrder.standardDegreeLEEquiv`: for a graded order, the same statement for the degree
  filtration.
* `MonomialOrder.affineHilbertFunction_eq_ncard_standardExponents`: for a graded order, the affine
  Hilbert function counts standard exponents; `MvPolynomial.affineHilbertFunction_eq_standard_count`
  is the `degLex` case.
* `MonomialOrder.exists_finset_standardExponents_iff`: finitely many forbidden exponents describe
  the standard exponents.
* `MvPolynomial.exists_eval_eq_affineHilbertFunction`: the affine Hilbert function is eventually a
  polynomial of degree at most `Nat.card σ`.
-/

@[expose] public section

noncomputable section

open MvPolynomial
open scoped MonomialOrder

namespace MonomialOrder

variable {σ k : Type*} [Field k] (m : MonomialOrder σ)

/-- The standard exponents of `I` for the monomial order `m`: the exponent vectors not divisible
by the leading exponent of any nonzero element of `I`. -/
def standardExponents (I : Ideal (MvPolynomial σ k)) : Set (σ →₀ ℕ) :=
  {e | ∀ p ∈ I, p ≠ 0 → ¬m.degree p ≤ e}

/-- The polynomials supported on the standard exponents of `I`. -/
def standardSpace (I : Ideal (MvPolynomial σ k)) : Submodule k (MvPolynomial σ k) :=
  restrictSupport k (m.standardExponents I)

/-- Standard exponents are closed under divisibility. -/
theorem isLowerSet_standardExponents (I : Ideal (MvPolynomial σ k)) :
    IsLowerSet (m.standardExponents I) :=
  fun _ _ hab hb p hp hp0 hpa ↦ hb p hp hp0 (hpa.trans hab)

/-- Every exponent is standard for the zero ideal. -/
@[simp]
theorem standardExponents_bot :
    m.standardExponents (⊥ : Ideal (MvPolynomial σ k)) = Set.univ :=
  Set.eq_univ_of_forall fun _ _ hp hp0 ↦ (hp0 (Ideal.mem_bot.mp hp)).elim

/-- No exponent is standard for the unit ideal, since `1` has leading exponent `0`. -/
@[simp]
theorem standardExponents_top :
    m.standardExponents (⊤ : Ideal (MvPolynomial σ k)) = ∅ :=
  Set.eq_empty_of_forall_notMem fun e he ↦
    he 1 Submodule.mem_top one_ne_zero (by rw [m.degree_one]; exact _root_.zero_le)

/-- For a principal ideal generated by `f ≠ 0`, the standard exponents are exactly those not
divisible by the leading exponent of `f`: leading exponents are additive on products, so every
nonzero multiple of `f` has a leading exponent divisible by that of `f`. -/
theorem mem_standardExponents_span_singleton {f : MvPolynomial σ k} (hf : f ≠ 0)
    {e : σ →₀ ℕ} :
    e ∈ m.standardExponents (Ideal.span {f}) ↔ ¬m.degree f ≤ e := by
  refine ⟨fun he ↦ he f (Ideal.mem_span_singleton_self f) hf, fun he p hp hp0 hle ↦ he ?_⟩
  obtain ⟨q, rfl⟩ := Ideal.mem_span_singleton'.mp hp
  have hq : q ≠ 0 := left_ne_zero_of_mul hp0
  rw [m.degree_mul hq hf] at hle
  exact le_add_self.trans hle

/-- A standard polynomial lying in `I` is zero: otherwise its leading exponent is a standard
exponent divisible by itself. -/
theorem eq_zero_of_mem_standardSpace_of_mem {I : Ideal (MvPolynomial σ k)}
    {p : MvPolynomial σ k} (hp : p ∈ m.standardSpace I) (hI : p ∈ I) : p = 0 := by
  by_contra hp0
  exact hp (m.degree_mem_support hp0) p hI hp0 le_rfl

/-- Every polynomial has a standard representative modulo `I` whose leading exponent is no larger
for `m`. This is division by the set of nonzero elements of `I`, whose leading coefficients are
units because `k` is a field. -/
theorem exists_mem_standardSpace_sub_mem (I : Ideal (MvPolynomial σ k))
    (p : MvPolynomial σ k) :
    ∃ q ∈ m.standardSpace I, p - q ∈ I ∧ m.degree q ≼[m] m.degree p := by
  classical
  let B : Set (MvPolynomial σ k) := {b | b ∈ I ∧ b ≠ 0}
  obtain ⟨g, q, hp, hdeg, hq⟩ :=
    m.div_set (B := B) (fun b hb ↦ m.isUnit_leadingCoeff.mpr hb.2) p
  have hsum : p - q = ∑ b ∈ g.support, g b • (b : MvPolynomial σ k) := by
    rw [hp, add_sub_cancel_right, Finsupp.linearCombination_apply, Finsupp.sum]
  refine ⟨q, fun e he b hbI hb0 ↦ hq e he b ⟨hbI, hb0⟩, ?_, ?_⟩
  · rw [hsum]
    exact I.sum_mem fun b _ ↦ I.smul_mem (g b) b.property.1
  · have hsum_le : m.degree (p - q) ≼[m] m.degree p := by
      rw [hsum]
      refine m.degree_sum_le.trans (Finset.sup_le fun b _ ↦ ?_)
      rw [smul_eq_mul, mul_comm]
      exact hdeg b
    have hq_eq : q = p - (p - q) := (sub_sub_cancel p q).symm
    rw [hq_eq]
    exact m.degree_sub_le.trans (sup_le le_rfl hsum_le)

/-- Two standard polynomials that are congruent modulo `I` are equal. -/
theorem eq_of_mem_standardSpace_of_sub_mem {I : Ideal (MvPolynomial σ k)}
    {p q : MvPolynomial σ k} (hp : p ∈ m.standardSpace I) (hq : q ∈ m.standardSpace I)
    (hpq : p - q ∈ I) : p = q :=
  sub_eq_zero.mp (m.eq_zero_of_mem_standardSpace_of_mem (sub_mem hp hq) hpq)

/-- The quotient map restricted to the standard space is a linear equivalence onto
`MvPolynomial σ k ⧸ I`: every quotient class has exactly one standard representative. -/
def standardQuotientEquiv (I : Ideal (MvPolynomial σ k)) :
    m.standardSpace I ≃ₗ[k] MvPolynomial σ k ⧸ I :=
  LinearEquiv.ofBijective ((Ideal.Quotient.mkₐ k I).toLinearMap.domRestrict (m.standardSpace I))
    ⟨fun p q hpq ↦ Subtype.ext
        (m.eq_of_mem_standardSpace_of_sub_mem p.2 q.2 (Ideal.Quotient.eq.mp hpq)),
      fun x ↦ by
        obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
        obtain ⟨q, hq, hpq, _⟩ := m.exists_mem_standardSpace_sub_mem I p
        exact ⟨⟨q, hq⟩, (Ideal.Quotient.eq.mpr hpq).symm⟩⟩

/-- `standardQuotientEquiv` sends a standard polynomial to its class modulo `I`. -/
@[simp]
theorem standardQuotientEquiv_apply (I : Ideal (MvPolynomial σ k)) (p : m.standardSpace I) :
    m.standardQuotientEquiv I p = Ideal.Quotient.mk I (p : MvPolynomial σ k) :=
  rfl

section Graded

variable {m}

/-- For a graded monomial order, the total degree of a polynomial is the degree of its leading
exponent. -/
theorem degree_degree_eq_totalDegree
    (hm : ∀ a b : σ →₀ ℕ, a ≼[m] b → a.degree ≤ b.degree) (f : MvPolynomial σ k) :
    (m.degree f).degree = f.totalDegree := by
  by_cases hf : f = 0
  · simp [hf]
  exact le_antisymm (le_totalDegree (m.degree_mem_support hf))
    (Finset.sup_le fun b hb ↦ hm _ _ (m.le_degree hb))

/-- For a graded monomial order, comparing leading exponents compares total degrees. -/
theorem totalDegree_le_of_degree_le
    (hm : ∀ a b : σ →₀ ℕ, a ≼[m] b → a.degree ≤ b.degree) {f g : MvPolynomial σ k}
    (h : m.degree f ≼[m] m.degree g) : f.totalDegree ≤ g.totalDegree := by
  rw [← degree_degree_eq_totalDegree hm, ← degree_degree_eq_totalDegree hm]
  exact hm _ _ h

/-- A polynomial supported on standard exponents of degree at most `N` is a standard polynomial of
total degree at most `N`, and conversely. -/
theorem mem_restrictSupport_standardExponents_degree_le_iff {I : Ideal (MvPolynomial σ k)}
    {N : ℕ} {p : MvPolynomial σ k} :
    p ∈ restrictSupport k {e | e ∈ m.standardExponents I ∧ e.degree ≤ N} ↔
      p ∈ m.standardSpace I ∧ p.totalDegree ≤ N := by
  simp only [standardSpace, mem_restrictSupport_iff, Set.subset_def, Finset.mem_coe,
    Set.mem_ofPred_eq, totalDegree, Finset.sup_le_iff]
  exact ⟨fun h ↦ ⟨fun e he ↦ (h e he).1, fun e he ↦ (h e he).2⟩,
    fun h e he ↦ ⟨h.1 e he, h.2 e he⟩⟩

/-- For a graded monomial order, the quotient map restricts to a linear equivalence from the
polynomials supported on standard exponents of degree at most `N` onto the `N`-th piece of the
quotient filtration. Surjectivity uses that division does not raise the total degree, which is
where the graded hypothesis enters. -/
def standardDegreeLEEquiv (hm : ∀ a b : σ →₀ ℕ, a ≼[m] b → a.degree ≤ b.degree)
    (I : Ideal (MvPolynomial σ k)) (N : ℕ) :
    restrictSupport k {e | e ∈ m.standardExponents I ∧ e.degree ≤ N} ≃ₗ[k]
      quotientDegreeLE I N :=
  LinearEquiv.ofBijective
    (((Ideal.Quotient.mkₐ k I).toLinearMap.domRestrict _).codRestrict (quotientDegreeLE I N)
      fun p ↦ mk_mem_quotientDegreeLE
        (mem_restrictSupport_standardExponents_degree_le_iff.mp p.2).2)
    ⟨fun p q hpq ↦ Subtype.ext (m.eq_of_mem_standardSpace_of_sub_mem
        (mem_restrictSupport_standardExponents_degree_le_iff.mp p.2).1
        (mem_restrictSupport_standardExponents_degree_le_iff.mp q.2).1
        (Ideal.Quotient.eq.mp (congrArg Subtype.val hpq))),
      fun x ↦ by
        obtain ⟨p, hp, hpx⟩ := mem_quotientDegreeLE.mp x.2
        obtain ⟨q, hq, hpq, hdeg⟩ := m.exists_mem_standardSpace_sub_mem I p
        refine ⟨⟨q, mem_restrictSupport_standardExponents_degree_le_iff.mpr
          ⟨hq, (totalDegree_le_of_degree_le hm hdeg).trans hp⟩⟩, Subtype.ext ?_⟩
        rw [← hpx]
        exact (Ideal.Quotient.eq.mpr hpq).symm⟩

/-- For a graded monomial order and finitely many variables, the affine Hilbert function counts
the standard exponents of degree at most `N`. The graded hypothesis is necessary: for the lex
order with `X 0 > X 1` and `I = span {X 0 - X 1 ^ 2}`, the class of `X 0` lies in the degree-one
piece but its standard representative `X 1 ^ 2` has degree two. -/
theorem affineHilbertFunction_eq_ncard_standardExponents [Finite σ]
    (hm : ∀ a b : σ →₀ ℕ, a ≼[m] b → a.degree ≤ b.degree) (I : Ideal (MvPolynomial σ k))
    (N : ℕ) :
    affineHilbertFunction I N =
      {e : σ →₀ ℕ | e ∈ m.standardExponents I ∧ e.degree ≤ N}.ncard := by
  rw [affineHilbertFunction, ← (standardDegreeLEEquiv hm I N).finrank_eq,
    Module.finrank_eq_nat_card_basis (basisRestrictSupport k _), Nat.card_coe_set_eq]

end Graded

/-- With finitely many variables, finitely many forbidden exponents describe the standard
exponents: an exponent is standard exactly when it lies above none of them. The forbidden set is
the set of minimal non-standard exponents, which is finite by Dickson's lemma
(`Finsupp.wellQuasiOrderedLE`). -/
theorem exists_finset_standardExponents_iff [Finite σ] (I : Ideal (MvPolynomial σ k)) :
    ∃ B : Finset (σ →₀ ℕ), ∀ e, e ∈ m.standardExponents I ↔ ∀ b ∈ B, ¬b ≤ e := by
  let bad : (σ →₀ ℕ) → Prop := fun e ↦ e ∉ m.standardExponents I
  have hfinite : {b | Minimal bad b}.Finite :=
    WellQuasiOrderedLE.finite_of_isAntichain fun a ha b hb hab hle ↦
      hab (le_antisymm hle (hb.2 ha.1 hle))
  refine ⟨hfinite.toFinset, fun e ↦ ⟨fun he b hb hbe ↦ ?_, fun he ↦ ?_⟩⟩
  · exact (hfinite.mem_toFinset.mp hb).1 (m.isLowerSet_standardExponents I hbe he)
  · by_contra hbad
    obtain ⟨b, hbe, hb⟩ := exists_minimal_le_of_wellFoundedLT bad e hbad
    exact he b (hfinite.mem_toFinset.mpr hb) hbe

end MonomialOrder

namespace MvPolynomial

variable {σ k : Type*} [Field k]

/-- The degree-lexicographic order is graded. -/
theorem degree_le_degree_of_degLex_le [LinearOrder σ] [WellFoundedGT σ] {a b : σ →₀ ℕ}
    (h : a ≼[MonomialOrder.degLex] b) : a.degree ≤ b.degree :=
  Finsupp.DegLex.monotone_degree h

/-- The affine Hilbert function counts the `degLex`-standard exponents of degree at most `N`. -/
theorem affineHilbertFunction_eq_standard_count [LinearOrder σ] [WellFoundedGT σ] [Finite σ]
    (I : Ideal (MvPolynomial σ k)) (N : ℕ) :
    affineHilbertFunction I N =
      {e : σ →₀ ℕ | e ∈ MonomialOrder.degLex.standardExponents I ∧ e.degree ≤ N}.ncard :=
  MonomialOrder.degLex.affineHilbertFunction_eq_ncard_standardExponents
    (fun _ _ ↦ degree_le_degree_of_degLex_le) I N

/-- In `n = Nat.card σ` variables, the polynomial ring itself has Hilbert function
`(N + n).choose n`. -/
theorem affineHilbertFunction_bot [Finite σ] (N : ℕ) :
    affineHilbertFunction (⊥ : Ideal (MvPolynomial σ k)) N =
      (N + Nat.card σ).choose (Nat.card σ) := by
  have := Fintype.ofFinite σ
  let _ : LinearOrder σ := LinearOrder.lift' _ (Fintype.equivFin σ).injective
  have : WellFoundedGT σ := Finite.to_wellFoundedGT
  rw [affineHilbertFunction_eq_standard_count, MonomialOrder.standardExponents_bot,
    ← Finsupp.ncard_setOf_degree_le]
  simp

/-- The affine Hilbert function of every ideal in finitely many variables agrees, for all large
`N`, with a polynomial over `K` of degree at most `Nat.card σ`, for every field `K` of
characteristic zero. The degree bound is attained by the zero ideal
(`affineHilbertFunction_bot`). -/
theorem exists_eval_eq_affineHilbertFunction (K : Type*) [Field K] [CharZero K] [Finite σ]
    (I : Ideal (MvPolynomial σ k)) :
    ∃ P : Polynomial K, P.natDegree ≤ Nat.card σ ∧
      ∃ N₀ : ℕ, ∀ N ≥ N₀, P.eval (N : K) = affineHilbertFunction I N := by
  have := Fintype.ofFinite σ
  let _ : LinearOrder σ := LinearOrder.lift' _ (Fintype.equivFin σ).injective
  have : WellFoundedGT σ := Finite.to_wellFoundedGT
  obtain ⟨B, hB⟩ := MonomialOrder.degLex.exists_finset_standardExponents_iff I
  obtain ⟨P, hdeg, hP⟩ := Finsupp.exists_eval_eq_ncard_forall_not_le K B
  refine ⟨P, hdeg, (B.sup id).degree, fun N hN ↦ ?_⟩
  rw [hP N hN, affineHilbertFunction_eq_standard_count]
  simp only [hB, and_comm]

end MvPolynomial
