/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import ArkLib.ToMathlib.RingTheory.Ideal.HeightUnder
import Mathlib.RingTheory.NoetherNormalization
import Mathlib.RingTheory.Int.Basic

/-!
# Acceptance tests for heights of contracted primes

These examples use the public API through an ordinary import. They compute the contraction of the
height-one prime `(2)` of `ℤ` along the identity extension, show that integrality is needed for
the lower bound (the height-one prime `(X)` of `ℚ[X]` contracts to `⊥` in `ℚ`), and derive the
source's `normalization_contraction_height_one` facts for a Noether normalization of an affine
domain.
-/

open Polynomial

namespace Ideal

/-- The prime `(2)` of `ℤ` has height one. -/
theorem height_span_two : (span {(2 : ℤ)}).height = 1 :=
  height_span_singleton_eq_one_of_mem_nonZeroDivisors
    (mem_nonZeroDivisors_of_ne_zero two_ne_zero) (by rw [Int.isUnit_iff]; norm_num)

/-- Along the identity extension of `ℤ`, the height-one prime `(2)` contracts to a height-one
prime generated by a prime element. -/
example : ((span {(2 : ℤ)}).under ℤ).height = 1 ∧
    ∃ a : ℤ, Prime a ∧ (span {(2 : ℤ)}).under ℤ = span {a} := by
  have : (span {(2 : ℤ)}).IsPrime :=
    (span_singleton_prime (by norm_num)).mpr (Int.prime_iff_natAbs_prime.mpr Nat.prime_two)
  exact ⟨height_under_eq_one _ height_span_two,
    exists_prime_under_eq_span_singleton _ height_span_two⟩

/-- Integrality is needed for `height_under_eq_one`: `ℚ[X]` is a domain containing the integrally
closed field `ℚ`, the prime `(X)` has height one, but its contraction to `ℚ` is `⊥`, of height
zero. The only hypothesis of `height_under_eq_one` that fails is `Algebra.IsIntegral ℚ ℚ[X]`. -/
example : (span {(X : ℚ[X])}).height = 1 ∧ ((span {(X : ℚ[X])}).under ℚ).height = 0 := by
  refine ⟨height_span_singleton_eq_one_of_mem_nonZeroDivisors
    (mem_nonZeroDivisors_of_ne_zero X_ne_zero) not_isUnit_X, ?_⟩
  have hne : (span {(X : ℚ[X])}).under ℚ ≠ ⊤ := by
    rw [Ne, under, comap_eq_top_iff, span_singleton_eq_top]
    exact not_isUnit_X
  rw [(eq_bot_or_top _).resolve_right hne, height_bot]

/-- Going down alone bounds the height of a contraction, with no integrality: `ℚ[X]` is flat over
`ℚ`, so it has going down, and the contraction of any prime has height at most its height. -/
example (P : Ideal ℚ[X]) [P.IsPrime] : (P.under ℚ).height ≤ P.height :=
  height_under_le_height P

/-- The source's `normalization_contraction_height_one` data, derived from the general theorems.
Let `g : MvPolynomial (Fin d) F →ₐ[F] A` be finite and injective with `A` a domain, and let `Q` be
a height-one prime of `A`. Then `Q.comap g` is prime, nonzero, of height one, and generated by a
prime polynomial, and the induced map of quotients is injective and finite. -/
example {F A : Type*} [Field F] [CommRing A] [IsDomain A] [Algebra F A] {d : ℕ}
    (g : MvPolynomial (Fin d) F →ₐ[F] A) (hinj : Function.Injective g) (hfin : g.Finite)
    (Q : Ideal A) [Q.IsPrime] (hQ : Q.height = 1) :
    (Q.comap (g : MvPolynomial (Fin d) F →+* A)).IsPrime ∧
      Q.comap (g : MvPolynomial (Fin d) F →+* A) ≠ ⊥ ∧
      (Q.comap (g : MvPolynomial (Fin d) F →+* A)).height = 1 ∧
      (∃ a, Prime a ∧ Q.comap (g : MvPolynomial (Fin d) F →+* A) = span {a}) ∧
      Function.Injective (quotientMap Q (g : MvPolynomial (Fin d) F →+* A) le_rfl) ∧
      (quotientMap Q (g : MvPolynomial (Fin d) F →+* A) le_rfl).Finite := by
  let _ : Algebra (MvPolynomial (Fin d) F) A := g.toRingHom.toAlgebra
  have : Module.Finite (MvPolynomial (Fin d) F) A := hfin
  have : FaithfulSMul (MvPolynomial (Fin d) F) A :=
    (faithfulSMul_iff_algebraMap_injective _ A).mpr hinj
  have hh : (Q.under (MvPolynomial (Fin d) F)).height = 1 := height_under_eq_one Q hQ
  refine ⟨comap_isPrime _ Q, ne_bot_of_height_eq_one hh, hh,
    exists_prime_under_eq_span_singleton Q hQ, quotientMap_injective, ?_⟩
  refine RingHom.Finite.of_comp_finite
    (f := Quotient.mk (Q.comap (g : MvPolynomial (Fin d) F →+* A))) ?_
  have hcomp : (quotientMap Q (g : MvPolynomial (Fin d) F →+* A) le_rfl).comp
      (Quotient.mk (Q.comap (g : MvPolynomial (Fin d) F →+* A))) =
        (Quotient.mk Q).comp (g : MvPolynomial (Fin d) F →+* A) :=
    RingHom.ext fun _ ↦ rfl
  rw [hcomp]
  exact RingHom.Finite.comp (RingHom.Finite.of_surjective _ Quotient.mk_surjective) hfin

end Ideal
