/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import ArkLib.Data.CodingTheory.ReedSolomon.ListDecoding.ExactOutput
import ArkLib.Data.CodingTheory.ReedSolomon.Agreement
import ArkLib.Data.CodingTheory.ReedSolomon.ListDecoding.Output.CandidateFilterSemantics
import ArkLib.Data.CodingTheory.ReedSolomon.Computation.RootFinding.Selection.JetPreparationMachine
import ArkLib.ToCompPoly.Univariate.Lagrange
import Mathlib.Data.Finset.Powerset
/-!
# Reference decoder from agreeing position subsets

This executable decoder enumerates `k`-subsets of the received positions, interpolates the unique
polynomial through each subset, checks its full agreement, and removes duplicate coefficient
vectors. It never enumerates field elements. The construction is exponential in the block length
and is intended as a correctness reference and as the bounded-length branch of faster decoders.
-/

namespace ReedSolomon.ListDecoding.PositionSubsetDecoder

open Polynomial JetHornerMachine
open CompPoly.CPolynomial

variable {F : Type*} [Field F] [DecidableEq F] [BEq F] [LawfulBEq F] {n : ℕ}

/-- The computable interpolation polynomial attached to a sample of received positions. -/
def interpolation (domain : Fin n ↪ F) (received : Fin n → F) (sample : Finset (Fin n)) :
    CompPoly.CPolynomial F :=
  CompPoly.CPolynomial.CLagrange.interpolate sample domain received

/-- Convert an ascending computable polynomial to the canonical descending vector of width `k`.
The zero-width case is the empty vector. -/
def coefficientVector (k : ℕ) (p : CompPoly.CPolynomial F) : List F :=
  match k with
  | 0 => []
  | k + 1 => HiddenDerivative.JetPreparationMachine.prepared k p.val.toList

private theorem interpolation_size_le (domain : Fin n ↪ F) (received : Fin n → F)
    (sample : Finset (Fin n)) {k : ℕ} (hcard : sample.card = k) :
    (interpolation domain received sample).val.size ≤ k := by
  let p := interpolation domain received sample
  have hdegreePoly : p.toPoly.degree < k := by
    dsimp [p, interpolation]
    rw [CompPoly.CPolynomial.CLagrange.cinterpolate_eq_interpolate]
    simpa [hcard] using
      (Lagrange.degree_interpolate_lt (s := sample) (v := domain) (r := received)
        domain.injective.injOn)
  have hdegree : p.degree < k := by
    rwa [CompPoly.CPolynomial.degree_toPoly]
  change p.val.size ≤ k
  cases hsize : p.val.size with
  | zero => simp [hsize]
  | succ m =>
      simp only [CompPoly.CPolynomial.degree, hsize] at hdegree
      exact Nat.succ_le_iff.mpr (by exact_mod_cast hdegree)

private theorem coefficientVector_length (k : ℕ) (p : CompPoly.CPolynomial F)
    (hsize : p.val.size ≤ k) : (coefficientVector k p).length = k := by
  cases k with
  | zero => simp [coefficientVector]
  | succ k =>
      simpa [coefficientVector] using
        (HiddenDerivative.JetPreparationMachine.prepared_length k p.val.toList (by simpa using hsize))

private theorem ascendingPolynomial_toList (p : CompPoly.CPolynomial F) :
    HiddenDerivative.JetPreparationMachine.ascendingPolynomial p.val.toList = p.toPoly := by
  ext j
  rw [HiddenDerivative.JetPreparationMachine.ascendingPolynomial_coeff,
    ← CompPoly.CPolynomial.coeff_toPoly]
  simp [CompPoly.CPolynomial.coeff, CompPoly.CPolynomial.Raw.coeff]

private theorem coefficientVector_polynomial (k : ℕ) (p : CompPoly.CPolynomial F)
    (hsize : p.val.size ≤ k) : coefficientPolynomial (coefficientVector k p) = p.toPoly := by
  cases k with
  | zero =>
      have hp : p = 0 := by
        apply CompPoly.CPolynomial.eq_zero_iff_coeff_zero.mpr
        intro i
        exact CompPoly.CPolynomial.coeff_eq_zero_of_size_le p (by omega)
      subst p
      simp [coefficientVector, coefficientPolynomial, CompPoly.CPolynomial.toPoly_zero]
  | succ k =>
      rw [coefficientVector, HiddenDerivative.JetPreparationMachine.prepared_polynomial,
        ascendingPolynomial_toList]

/-- Candidate generated by interpolating one position sample. -/
def sampleCandidate (domain : Fin n ↪ F) (received : Fin n → F) (k : ℕ)
    (sample : Finset (Fin n)) : List F :=
  coefficientVector k (interpolation domain received sample)

/-- A sample of cardinality `k` produces exactly the repository's physical output width. -/
theorem sampleCandidate_length (domain : Fin n ↪ F) (received : Fin n → F)
    (k : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) :
    (sampleCandidate domain received k sample).length = k := by
  exact coefficientVector_length k _ (interpolation_size_le domain received sample hcard)

/-- The materialized vector represents the mathematical Lagrange interpolant of the sample. -/
theorem sampleCandidate_polynomial (domain : Fin n ↪ F) (received : Fin n → F)
    (k : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) :
    coefficientPolynomial (sampleCandidate domain received k sample) =
      Lagrange.interpolate sample domain received := by
  rw [sampleCandidate, coefficientVector_polynomial k _
    (interpolation_size_le domain received sample hcard)]
  exact CompPoly.CPolynomial.CLagrange.cinterpolate_eq_interpolate

/-- All `k`-subsets of the materialized positions, in the finset's executable canonical order. -/
def samples (n k : ℕ) : List (Finset (Fin n)) :=
  (List.sublistsLen k (List.ofFn id)).map List.toFinset

/-- The executable list contains exactly the `k`-element sets of input positions. -/
theorem mem_samples_iff (sample : Finset (Fin n)) (k : ℕ) :
    sample ∈ samples n k ↔ sample.card = k := by
  constructor
  · intro hsample
    rcases List.mem_map.mp hsample with ⟨positions, hpositions, hset⟩
    have hspec := List.mem_sublistsLen.mp hpositions
    have hnodup : positions.Nodup :=
      (List.nodup_ofFn.mpr Function.injective_id).sublist hspec.1
    rw [← hset, List.toFinset_card_of_nodup hnodup, hspec.2]
  · intro hcard
    let positions := (List.ofFn id).filter fun i ↦ i ∈ sample
    have hsub : List.Sublist positions (List.ofFn id) := List.filter_sublist
    have hnodup : positions.Nodup :=
      (List.nodup_ofFn.mpr Function.injective_id).filter _
    have hset : positions.toFinset = sample := by
      ext i
      simp [positions]
    have hlength : positions.length = k := by
      rw [← List.toFinset_card_of_nodup hnodup, hset, hcard]
    exact List.mem_map.mpr ⟨positions, List.mem_sublistsLen.mpr ⟨hsub, hlength⟩, hset⟩

/-- Execute interpolation and the existing degree/agreement filter for one sample. -/
def checkedCandidate (domain : Fin n ↪ F) (received : Fin n → F) (k A : ℕ)
    (sample : Finset (Fin n)) : Option (List F) :=
  CandidateFilterMachine.result k k A (sampleCandidate domain received k sample)
    (List.ofFn fun i ↦ (domain i, received i))

/-- Reference decoder obtained by checking every position-subset interpolation and deduplicating. -/
def run (domain : Fin n ↪ F) (received : Fin n → F) (k A : ℕ) : List (List F) :=
  ((samples n k).filterMap (checkedCandidate domain received k A)).dedup

private theorem mem_run_iff (domain : Fin n ↪ F) (received : Fin n → F) (k A : ℕ)
    (cs : List F) :
    cs ∈ run domain received k A ↔
      ∃ sample : Finset (Fin n), sample.card = k ∧
        checkedCandidate domain received k A sample = some cs := by
  simp [run, mem_samples_iff]

/-- A successful sample check returns a fixed-width vector for the sample interpolant that passes
the degree and full received-word agreement tests. -/
theorem checkedCandidate_properties (domain : Fin n ↪ F) (received : Fin n → F)
    (k A : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) (cs : List F)
    (hchecked : checkedCandidate domain received k A sample = some cs) :
    cs.length = k ∧
      coefficientPolynomial cs = Lagrange.interpolate sample domain received ∧
      (coefficientPolynomial cs).degree < k ∧
      A ≤ Code.agree (evalOnPoints domain (coefficientPolynomial cs)) received := by
  have hsource := sampleCandidate_length domain received k sample hcard
  have hrepresented := CandidateFilterMachine.result_represents hsource le_rfl hchecked
  have hchecked' : CandidateFilterMachine.result k k A
      (sampleCandidate domain received k sample)
      (List.ofFn fun i ↦ (domain i, received i)) = some cs := hchecked
  have haccepted := (CandidateFilterMachine.result_ne_none_iff k k A
    (sampleCandidate domain received k sample) hsource le_rfl domain received).mp (by
      rw [hchecked']
      simp)
  exact ⟨hrepresented.1,
    hrepresented.2.trans (sampleCandidate_polynomial domain received k sample hcard),
    hrepresented.2 ▸ haccepted.1, hrepresented.2 ▸ haccepted.2⟩

/-- If a sample candidate meets the full received-word agreement threshold, checking that sample
returns the candidate itself. -/
theorem checkedCandidate_of_agreement (domain : Fin n ↪ F)
    (received : Fin n → F) (k A : ℕ) (sample : Finset (Fin n))
    (hcard : sample.card = k)
    (hagreement : A ≤ Code.agree
      (evalOnPoints domain (coefficientPolynomial (sampleCandidate domain received k sample)))
      received) :
    checkedCandidate domain received k A sample =
      some (sampleCandidate domain received k sample) := by
  have hlength := sampleCandidate_length domain received k sample hcard
  have hdegree :
      (coefficientPolynomial (sampleCandidate domain received k sample)).degree < k := by
    simpa only [hlength] using
      degree_coefficientPolynomial_lt_length (sampleCandidate domain received k sample)
  have hsome := (CandidateFilterMachine.result_ne_none_iff k k A
    (sampleCandidate domain received k sample) hlength le_rfl domain received).mpr
      ⟨hdegree, hagreement⟩
  cases hresult : checkedCandidate domain received k A sample with
  | none => exact (hsome (by simpa [checkedCandidate] using hresult)).elim
  | some out =>
      have hrepresented := CandidateFilterMachine.result_represents hlength le_rfl hresult
      have hout : out = sampleCandidate domain received k sample :=
        coefficientVectors_eq (hrepresented.1.trans hlength.symm) hrepresented.2
      simpa [hout] using hresult

/-- A polynomial of degree below the sample cardinality equals the sample interpolant whenever it
agrees with the received word at every sampled position. -/
theorem interpolate_eq_of_agrees_on (domain : Fin n ↪ F) (received : Fin n → F)
    (k : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) (P : F[X])
    (hdegree : P.degree < k) (hagreement : sample ⊆ polynomialAgreementSet domain received P) :
    Lagrange.interpolate sample domain received = P := by
  apply Polynomial.eq_of_degrees_lt_of_eval_index_eq sample domain.injective.injOn
  · simpa [hcard] using
      Lagrange.degree_interpolate_lt (s := sample) (v := domain) (r := received)
        domain.injective.injOn
  · simpa [hcard] using hdegree
  · intro i hi
    rw [Lagrange.eval_interpolate_at_node received domain.injective.injOn hi]
    exact (Finset.mem_filter.mp (hagreement hi)).2.symm

private theorem exists_mem_run_polynomial (domain : Fin n ↪ F) (received : Fin n → F)
    (k A : ℕ) (hAk : k ≤ A) (P : F[X]) (hdegree : P.degree < k)
    (hagreement : A ≤ Code.agree (evalOnPoints domain P) received) :
    ∃ cs ∈ run domain received k A, coefficientPolynomial cs = P := by
  have hcardAgreement : A ≤ (polynomialAgreementSet domain received P).card := by
    change A ≤ ({i : Fin n | P.eval (domain i) = received i} : Finset (Fin n)).card at hagreement
    change A ≤ ({i : Fin n | P.eval (domain i) = received i} : Finset (Fin n)).card
    exact hagreement
  obtain ⟨sample, hsample, hcard⟩ :=
    Finset.exists_subset_card_eq (hAk.trans hcardAgreement)
  have hinterpolation : Lagrange.interpolate sample domain received = P :=
    interpolate_eq_of_agrees_on domain received k sample hcard P hdegree hsample
  have hcandidate : coefficientPolynomial (sampleCandidate domain received k sample) = P :=
    (sampleCandidate_polynomial domain received k sample hcard).trans hinterpolation
  have hcandidateAgreement :
      A ≤ Code.agree
        (evalOnPoints domain
          (coefficientPolynomial (sampleCandidate domain received k sample))) received := by
    rwa [hcandidate]
  have hchecked := checkedCandidate_of_agreement domain received k A sample hcard
    hcandidateAgreement
  exact ⟨sampleCandidate domain received k sample,
    (mem_run_iff domain received k A _).mpr ⟨sample, hcard, hchecked⟩, hcandidate⟩

/-- The actual position-subset decoder returns exactly the duplicate-free fixed-width agreement
list whenever the threshold supplies at least `k` agreeing positions per wanted message. -/
theorem run_exact (domain : Fin n ↪ F) (received : Fin n → F) (k A : ℕ) (hAk : k ≤ A) :
    ExactOutput domain received k A (run domain received k A) := by
  let out := run domain received k A
  have hvector (cs : List F) :
      cs ∈ out ↔ cs.length = k ∧ (coefficientPolynomial cs).degree < k ∧
        A ≤ Code.agree (evalOnPoints domain (coefficientPolynomial cs)) received := by
    constructor
    · intro hcs
      rcases (mem_run_iff domain received k A cs).mp hcs with
        ⟨sample, hcard, hchecked⟩
      have hp := checkedCandidate_properties domain received k A sample hcard cs hchecked
      exact ⟨hp.1, hp.2.2⟩
    · rintro ⟨hlength, hdegree, hagreement⟩
      obtain ⟨candidate, hcandidateMem, hcandidatePolynomial⟩ :=
        exists_mem_run_polynomial domain received k A hAk (coefficientPolynomial cs)
          hdegree hagreement
      rcases (mem_run_iff domain received k A candidate).mp hcandidateMem with
        ⟨sample, hcard, hchecked⟩
      have hcandidateLength :=
        (checkedCandidate_properties domain received k A sample hcard candidate hchecked).1
      have heq : candidate = cs :=
        coefficientVectors_eq (hcandidateLength.trans hlength.symm) hcandidatePolynomial
      change cs ∈ run domain received k A
      rw [← heq]
      exact hcandidateMem
  have houtNodup : out.Nodup := by
    exact List.nodup_dedup _
  have hpolynomialNodup : (out.map coefficientPolynomial).Nodup := by
    apply houtNodup.map_on
    intro xs hxs ys hys hpoly
    exact coefficientVectors_eq ((hvector xs).mp hxs |>.1 |>.trans ((hvector ys).mp hys |>.1).symm)
      hpoly
  refine ⟨hpolynomialNodup, houtNodup, ?_, hvector⟩
  intro P
  constructor
  · intro hP
    rcases List.mem_map.mp hP with ⟨cs, hcs, rfl⟩
    exact (hvector cs).mp hcs |>.2
  · rintro ⟨hdegree, hagreement⟩
    obtain ⟨cs, hcs, hpoly⟩ :=
      exists_mem_run_polynomial domain received k A hAk P hdegree hagreement
    exact List.mem_map.mpr ⟨cs, hcs, hpoly⟩

end ReedSolomon.ListDecoding.PositionSubsetDecoder
