/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.Data.MvPolynomial.BoxAlgebra
public import Mathlib.RingTheory.Ideal.Operations
public import Mathlib.RingTheory.Nilpotent.Basic

/-!
# Nilpotence of the parameter ideal

The whole parameter ideal has exponent `r * (N - 1) + 1`. This bound accounts for
mixed parameter products and does not confuse coordinatewise truncation with total-degree
truncation.
-/

@[expose] public section

namespace CPoly.BoxAlgebra

variable {r N : ℕ} {R : Type*} [CommRing R] [BEq R] [LawfulBEq R]

/-- The ideal generated by all stored nilpotent parameters. -/
def parameterIdeal : Ideal (Carrier r N R) := Ideal.span (Set.range eps)

private theorem sum_pow_eq_zero {A ι : Type*} [CommSemiring A]
    (s : Finset ι) (f : ι → A) (N : ℕ) (hN : 0 < N)
    (hf : ∀ i ∈ s, f i ^ N = 0) :
    (∑ i ∈ s, f i) ^ (s.card * (N - 1) + 1) = 0 := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
    rw [Finset.sum_insert hi, Finset.card_insert_of_notMem hi]
    apply (Commute.all _ _).add_pow_eq_zero_of_add_le_succ_of_pow_eq_zero
      (hf i (Finset.mem_insert_self i s))
      (ih (fun j hj => hf j (Finset.mem_insert_of_mem hj)))
    simp only [Nat.add_mul, one_mul]
    omega

/-- A single bound annihilates the entire ideal, including products of distinct parameters. -/
theorem parameterIdeal_pow (hN : 0 < N) :
    (parameterIdeal (r := r) (N := N) (R := R)) ^ (r * (N - 1) + 1) = ⊥ := by
  have h := sum_pow_eq_zero (Finset.univ : Finset (Fin r))
    (fun i => Ideal.span ({eps i} : Set (Carrier r N R))) N hN (by
      intro i _
      rw [Ideal.span_singleton_pow, eps_pow]
      simp)
  simpa [parameterIdeal, Ideal.span_range_eq_iSup, Ideal.sum_eq_sup,
    Finset.sup_univ_eq_iSup] using h

/-- Every residual in the parameter ideal obeys the whole-ideal exponent. -/
theorem pow_eq_zero_of_mem_parameterIdeal (hN : 0 < N) (p : Carrier r N R)
    (hp : p ∈ parameterIdeal) : p ^ (r * (N - 1) + 1) = 0 := by
  exact Ideal.pow_eq_zero_of_mem (parameterIdeal_pow hN) le_rfl hp

/-- Executable extraction of the constant parameter coefficient. -/
def constantValue (p : Carrier r N R) : R :=
  p.val.coeff (CMvMonomial.ofFinsupp 0)

private theorem constantValue_reduce (hN : 0 < N) (p : CMvPolynomial r R) :
    constantValue (reduce (N := N) p) =
      MvPolynomial.constantCoeff (fromCMvPolynomial p) := by
  change MvPolynomial.coeff 0 (fromCMvPolynomial (BoxTruncation.truncate N p)) = _
  simp [BoxTruncation.coeff_semantics, hN, MvPolynomial.constantCoeff_eq]

/-- Specialization at zero parameters, implemented on stored coefficients. -/
def constantSpecialization (hN : 0 < N) : Carrier r N R →+* R where
  toFun := constantValue
  map_zero' := by
    change constantValue (reduce 0) = 0
    rw [constantValue_reduce hN, CPoly.map_zero, _root_.map_zero]
  map_one' := by
    change constantValue (reduce 1) = 1
    rw [constantValue_reduce hN, CPoly.map_one, _root_.map_one]
  map_add' p q := by
    change constantValue (reduce (p.val + q.val)) = _
    rw [constantValue_reduce hN, CPoly.map_add, _root_.map_add]
    rfl
  map_mul' p q := by
    change constantValue (reduce (p.val * q.val)) = _
    rw [constantValue_reduce hN, CPoly.map_mul, _root_.map_mul]
    rfl

@[simp] theorem constantSpecialization_eps (hN : 0 < N) (i : Fin r) :
    constantSpecialization (R := R) hN (eps i) = 0 := by
  change constantValue (reduce (CMvPolynomial.X i)) = 0
  rw [constantValue_reduce hN, CMvPolynomial.fromCMvPolynomial_X,
    MvPolynomial.constantCoeff_X]

/-- Every parameter-ideal element specializes to zero. -/
theorem parameterIdeal_le_ker (hN : 0 < N) :
    parameterIdeal ≤ RingHom.ker (constantSpecialization (r := r) (R := R) hN) := by
  apply Ideal.span_le.mpr
  rintro _ ⟨i, rfl⟩
  exact constantSpecialization_eps hN i

omit [BEq R] [LawfulBEq R] in
private theorem sub_constant_mem {A : Type*} [CommRing A]
    (f : MvPolynomial (Fin r) R →+* A) (p : MvPolynomial (Fin r) R) :
    f p - f (MvPolynomial.C (MvPolynomial.constantCoeff p)) ∈
      Ideal.span (Set.range (fun i => f (MvPolynomial.X i))) := by
  induction p using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq =>
    simpa only [_root_.map_add, add_sub_add_comm] using Ideal.add_mem _ hp hq
  | mul_X p i _ =>
    simp only [_root_.map_mul, MvPolynomial.constantCoeff_X, mul_zero, _root_.map_zero, sub_zero]
    exact Ideal.mul_mem_left _ _ (Ideal.mem_span_range_self (x := i))

/-- Zero constant term is exactly membership in the parameter ideal. -/
theorem ker_constantSpecialization (hN : 0 < N) :
    RingHom.ker (constantSpecialization (r := r) (R := R) hN) = parameterIdeal := by
  apply le_antisymm _ (parameterIdeal_le_ker hN)
  intro p hp
  let f : MvPolynomial (Fin r) R →+* Carrier r N R :=
    projection.comp polyRingEquiv.symm.toRingHom
  have hf (q : CMvPolynomial r R) : f (fromCMvPolynomial q) = reduce q := by
    change projection (polyRingEquiv.symm (polyRingEquiv q)) = _
    rw [RingEquiv.symm_apply_apply]
    rfl
  have hX (i : Fin r) : f (MvPolynomial.X i) = eps i := by
    rw [← CMvPolynomial.fromCMvPolynomial_X, hf]
    rfl
  have hc : MvPolynomial.constantCoeff (fromCMvPolynomial p.val) = 0 := hp
  have h := sub_constant_mem f (fromCMvPolynomial p.val)
  simpa only [hf, reduce_val, hc, _root_.map_zero, sub_zero, hX, parameterIdeal] using h

/-- The whole constant-specialization kernel has the same uniform nilpotence bound. -/
theorem constantSpecialization_ker_pow (hN : 0 < N) :
    RingHom.ker (constantSpecialization (r := r) (R := R) hN) ^
      (r * (N - 1) + 1) = ⊥ := by
  rw [ker_constantSpecialization, parameterIdeal_pow hN]

/-- A zero constant parameter residual is nilpotent at the whole-ideal exponent. -/
theorem pow_eq_zero_of_constantValue_eq_zero (hN : 0 < N) (p : Carrier r N R)
    (hp : constantValue p = 0) : p ^ (r * (N - 1) + 1) = 0 := by
  apply pow_eq_zero_of_mem_parameterIdeal hN p
  rw [← ker_constantSpecialization hN]
  exact hp

end CPoly.BoxAlgebra
